export type GinKlassifikatsiya = {
  slug: string
  nom: string
  toliq?: string
  kategoriya: string
  yangilanish: string
  qisqa: string
  tushuntirish: string
  qachon: string
  ustunlar: string[]
  qatorlar: string[][]
  eslabQolish: string
  ehtiyot: string
  manbalar: { nom: string; url: string }[]
}

export const GIN_KLASSIFIKATSIYA_KATEGORIYALARI = [
  'Hammasi',
  'Umumiy ginekologiya',
  'Reproduktiv tibbiyot',
  'Onkoginekologiya',
  'Uroginekologiya',
  'Akusherlik',
] as const

export const GINEKOLOGIYA_KLASSIFIKATSIYALARI: GinKlassifikatsiya[] = [
  {
    slug: 'figo-aub-system-1', nom: 'FIGO AUB System 1', toliq: 'Normal va anomal bachadon qon ketishi terminlari',
    kategoriya: 'Umumiy ginekologiya', yangilanish: 'FIGO 2018',
    qisqa: "Hayz qon ketishini chastota, muntazamlik, davomiylik va hajm bo'yicha bir xil tilda tavsiflaydi.",
    tushuntirish: "Bu tizim sababni aytmaydi. Avval qon ketish naqshini aniq nomlaydi, keyin sabab PALM-COEIN bilan izlanadi. 'Menorragiya' kabi noaniq eski atamalar o'rniga og'ir, cho'zilgan yoki nomuntazam qon ketish deyiladi.",
    qachon: "Reproduktiv yoshdagi, homilador bo'lmagan bemorda hayz anamnezini standart yozishda.",
    ustunlar: ['Belgi', 'Normal diapazon', 'Anomal holat'], qatorlar: [
      ['Chastota', '24-38 kun', 'Tez-tez <24 kun; siyrak >38 kun'],
      ['Muntazamlik', 'Sikl farqi yoshga mos chegarada', 'Sikllar orasidagi farq meʼyordan katta'],
      ['Davomiylik', '8 kungacha', '8 kundan uzoq'],
      ['Hajm', "Bemor hayotiga xalaqit bermaydi", "Hayot sifatini buzadigan ko'p qon ketish"],
    ],
    eslabQolish: "System 1 qon ketishning qandayligini, System 2 PALM-COEIN esa nega bo'layotganini tushuntiradi.",
    ehtiyot: "Homiladorlik bilan bog'liq qon ketish bu tizimga kirmaydi. Hajmni faqat millilitr bilan emas, hayot sifatiga ta'siri bilan baholash muhim.",
    manbalar: [{ nom: 'FIGO AUB systems 2018 revision', url: 'https://doi.org/10.1002/ijgo.12666' }],
  },
  {
    slug: 'palm-coein', nom: 'PALM-COEIN', toliq: 'Anomal bachadon qon ketishi sabablari',
    kategoriya: 'Umumiy ginekologiya', yangilanish: 'FIGO 2018',
    qisqa: "Anomal bachadon qon ketishi sabablarini struktur va nostruktur guruhlarga ajratadi.",
    tushuntirish: "PALM ko'rish yoki gistologiya bilan aniqlanadigan struktur sabablar, COEIN esa ko'pincha funksional yoki tizimli sabablar. Bir bemorda bir nechta sabab birga bo'lishi mumkin.",
    qachon: "Homilador bo'lmagan reproduktiv yoshdagi bemorda AUB sababini yozish va tekshiruv rejasini tuzishda.",
    ustunlar: ['Kod', 'Sabab', 'Talabaga sodda maʼnosi'], qatorlar: [
      ['P', 'Polyp', "Endometriy yoki serviks polipi"], ['A', 'Adenomyosis', "Endometriy bezlari miometriy ichida"],
      ['L', 'Leiomyoma', "Mioma; submukoz va boshqa turlarga ajratiladi"], ['M', 'Malignancy and hyperplasia', "Giperplaziya yoki saraton"],
      ['C', 'Coagulopathy', "Qon ivish buzilishi"], ['O', 'Ovulatory dysfunction', "Ovulyatsiya buzilishi"],
      ['E', 'Endometrial', "Mahalliy endometrial gemostaz buzilishi"], ['I', 'Iatrogenic', "Dori yoki tibbiy vosita bilan bog'liq"],
      ['N', 'Not otherwise classified', "Hozirgi guruhlarga kirmaydigan sabab"],
    ],
    eslabQolish: "PALM struktur, COEIN nostruktur. Piktogrammadagi kaft so'zi PALMni esda qoldiradi.",
    ehtiyot: "PALM-COEIN tashxisning o'zi emas; homiladorlik testi va xavfli qon ketishni birinchi navbatda baholash kerak.",
    manbalar: [{ nom: 'FIGO PALM-COEIN 2018 revision', url: 'https://doi.org/10.1002/ijgo.12666' }],
  },
  {
    slug: 'figo-leiomyoma', nom: 'FIGO leiomioma turlari', toliq: 'Miomaning endometriy va serozaga munosabati',
    kategoriya: 'Umumiy ginekologiya', yangilanish: 'FIGO 2018',
    qisqa: "Miomani bachadon devoridagi joylashuviga qarab 0 dan 8 gacha tasniflaydi.",
    tushuntirish: "Raqam kichiklashgan sari tugun bachadon bo'shlig'iga, kattalashgan sari tashqi serozaga yaqinlashadi. Bu qon ketish ehtimoli va operatsion kirish yo'lini tushunishga yordam beradi.",
    qachon: "UTT, MRT, gisteroskopiya xulosasi va miomektomiya rejasini standart yozishda.",
    ustunlar: ['Tur', 'Joylashuvi'], qatorlar: [
      ['0', "To'liq bo'shliqda, oyoqchali submukoz"], ['1', "Submukoz; <50% intramural"], ['2', "Submukoz; ≥50% intramural"],
      ['3', "Endometriyga tegib turadi, lekin bo'shliqqa chiqmaydi"], ['4', "To'liq intramural"],
      ['5', "Subseroz; ≥50% intramural"], ['6', "Subseroz; <50% intramural"], ['7', "Oyoqchali subseroz"],
      ['8', "Boshqa joy: servikal, parazitar va boshqalar"], ['2-5', "Gibrid: endometriy va serozaga munosabat ikki raqam bilan"],
    ],
    eslabQolish: "0-2 submukoz, 3 endometriyga tegadi, 4 devor ichida, 5-7 subseroz, 8 boshqa.",
    ehtiyot: "Gibrid tugunda birinchi raqam endometriyga, ikkinchisi serozaga munosabatni bildiradi.",
    manbalar: [{ nom: 'FIGO leiomyoma subclassification 2018', url: 'https://doi.org/10.1002/ijgo.12666' }],
  },
  {
    slug: 'endometrioz-rasrm', nom: 'rASRM endometrioz bosqichlari', toliq: 'Revised American Society for Reproductive Medicine classification',
    kategoriya: 'Reproduktiv tibbiyot', yangilanish: 'rASRM 1996 amaldagi jarrohlik tizimi',
    qisqa: "Laparoskopik o'choq, bitishma va endometriomalarni ball bilan I-IV bosqichga ajratadi.",
    tushuntirish: "Jarroh ko'rgan o'choqlarning joyi va chuqurligi, tuxumdon hamda nay atrofidagi bitishmalar ballanadi. Bosqich anatomik tarqalishni ko'rsatadi, og'riq og'irligini emas.",
    qachon: "Endometrioz laparoskopiyada aniqlanganda operatsion topilmani standart qayd etishda.",
    ustunlar: ['Bosqich', 'Ball', 'Mazmuni'], qatorlar: [
      ['I', '1-5', 'Minimal'], ['II', '6-15', 'Yengil'], ['III', '16-40', "O'rta"], ['IV', '>40', "Og'ir"],
    ],
    eslabQolish: "I-II yuzaki va kam, III-IV endometrioma hamda zich bitishmalar ko'proq.",
    ehtiyot: "Bosqich og'riq, bepushtlik yoki davolash zaruratini yakka o'zi bashorat qilmaydi. Chuqur endometrioz uchun #Enzian ko'proq anatomik ma'lumot beradi.",
    manbalar: [{ nom: 'ASRM revised classification of endometriosis', url: 'https://doi.org/10.1016/S0015-0282(16)58175-X' }],
  },
  {
    slug: 'enzian', nom: '#Enzian endometrioz tasnifi', toliq: 'Chuqur va barcha anatomik endometrioz shakllari',
    kategoriya: 'Reproduktiv tibbiyot', yangilanish: '#Enzian 2021',
    qisqa: "Chuqur endometriozning qaysi kompartment va a'zolarga tarqalganini xarita kabi yozadi.",
    tushuntirish: "A rektovaginal soha va vagina, B uterosakral bog'lam va chanoq yon devori, C rektum. Qo'shimcha kodlar peritoneum, tuxumdon, nay, adenomioz va boshqa a'zolarni ko'rsatadi.",
    qachon: "UTT/MRT xaritalash, operatsiyani rejalash va jarrohlik topilmalarini qayd etishda.",
    ustunlar: ['Kod', 'Hudud', "O'lcham darajasi"], qatorlar: [
      ['A', 'Rektovaginal septum va vagina', '1 <1 sm; 2 =1-3 sm; 3 >3 sm'], ['B', 'Uterosakral bogʻlam va chanoq yon devori', '1/2/3'],
      ['C', 'Rektum', '1/2/3'], ['P', 'Peritoneal endometrioz', 'P1-P3'], ['O', 'Tuxumdon endometriozi', 'O1-O3'],
      ['T', 'Nay va tubo-ovarial bitishma', 'T1-T3'], ['Adenomyosis', 'Bachadon adenomiozi', 'FA'], ['F', "Boshqa a'zolar", 'Ichak, qovuq, ureter va boshqalar'],
    ],
    eslabQolish: "A-B-C markaziy uch zona; P-O-T reproduktiv anatomiyani; F boshqa a'zolarni yozadi.",
    ehtiyot: "# belgisi 2021-yilgi kengaytirilgan Enzian tizimini bildiradi. Lokal protokolda eski Enzian ishlatilsa farq ko'rsatilishi kerak.",
    manbalar: [{ nom: '#Enzian classification 2021', url: 'https://doi.org/10.1007/s00404-020-05946-7' }],
  },
  {
    slug: 'pcos-fenotiplari', nom: 'PCOS Rotterdam fenotiplari', toliq: 'Polikistik tuxumdon sindromi A-D fenotiplari',
    kategoriya: 'Reproduktiv tibbiyot', yangilanish: 'International PCOS Guideline 2023',
    qisqa: "Giperandrogenizm, ovulyatsiya buzilishi va polikistik tuxumdon belgilarining kombinatsiyasini ko'rsatadi.",
    tushuntirish: "Boshqa sabablar chiqarib tashlangach, kattalarda uch mezondan ikkitasi PCOS tashxisini qo'llab-quvvatlaydi. Fenotip qaysi mezonlar borligini ixcham yozadi.",
    qachon: "PCOS tashxisini tushuntirish, metabolik va reproduktiv xavfni tizimli baholashda.",
    ustunlar: ['Fenotip', 'Giperandrogenizm', 'Ovulyatsiya buzilishi', 'PCOM yoki AMH'], qatorlar: [
      ['A', 'Bor', 'Bor', 'Bor'], ['B', 'Bor', 'Bor', "Yo'q"], ['C', 'Bor', "Yo'q", 'Bor'], ['D', "Yo'q", 'Bor', 'Bor'],
    ],
    eslabQolish: "A uchalasi; Bda tuxumdon morfologiyasi yo'q; C ovulyator; D giperandrogenizmsiz.",
    ehtiyot: "O'smirda UTT va AMH tashxis uchun tavsiya etilmaydi. 2023 qo'llanmada kattalarda AMH UTTga muqobil bo'lishi mumkin, lekin ikkalasini birga qo'shib ortiqcha tashxis qilinmaydi.",
    manbalar: [{ nom: 'International evidence-based PCOS guideline 2023', url: 'https://www.monash.edu/medicine/mchri/pcos/guideline' }],
  },
  {
    slug: 'endometrial-giperplaziya-who', nom: 'WHO endometrial giperplaziya tasnifi',
    kategoriya: 'Onkoginekologiya', yangilanish: 'WHO 2020',
    qisqa: "Endometrial giperplaziyani atipiyasiz giperplaziya va EIN/atipik giperplaziyaga ajratadi.",
    tushuntirish: "Yangi ikki guruhli tizim eski simple/complex atamalaridan klinik jihatdan aniqroq. Asosiy savol atipiya yoki endometrioid intraepitelial neoplaziya bormi, chunki saratonga o'tish xavfi va davolash keskin farq qiladi.",
    qachon: "Endometrial biopsiya yoki kyuretaj gistologik xulosasini talqin qilishda.",
    ustunlar: ['Toifa', 'Mazmuni', 'Amaliy ahamiyati'], qatorlar: [
      ['Atipiyasiz giperplaziya', "Bezlar ko'paygan, sitologik atipiya yo'q", "Ko'pincha progestin va kuzatuv"],
      ['EIN yoki atipik giperplaziya', 'Klonaviy atipik prekursor', "Birga saraton bo'lishi mumkin; onkoginekologik taktika"],
    ],
    eslabQolish: "Hozirgi tizimning markaziy savoli: atipiya bor yoki yo'q.",
    ehtiyot: "EIN/atipik giperplaziya bilan bir vaqtda yashirin endometrial saraton bo'lishi mumkin. Yakuniy qaror patolog va klinik kontekstga bog'liq.",
    manbalar: [{ nom: 'WHO Classification Female Genital Tumours 5th edition', url: 'https://tumourclassification.iarc.who.int/chapters/34' }],
  },
  {
    slug: 'bethesda-servikal-sitologiya', nom: 'Bethesda servikal sitologiya tizimi',
    kategoriya: 'Onkoginekologiya', yangilanish: 'Bethesda 2014 amaldagi nomenklatura',
    qisqa: "Pap-test natijasini standart epitelial va bez hujayra toifalarida yozadi.",
    tushuntirish: "Avval namuna yetarliligi, keyin intraepitelial leziya yoki malignlik bor-yo'qligi, so'ng aniq anomaliya yoziladi. Bu gistologik CIN bosqichi emas.",
    qachon: "Servikal sitologiya hisobotini o'qish va ASCCP riskiga kiritishda.",
    ustunlar: ['Guruh', 'Qisqartma', 'Sodda maʼno'], qatorlar: [
      ['Manfiy', 'NILM', "Intraepitelial leziya yoki malignlik yo'q"], ['Yassi hujayra', 'ASC-US', "Ahamiyati noaniq atipiya"],
      ['Yassi hujayra', 'ASC-H', "HSILni inkor qilib bo'lmaydi"], ['Yassi hujayra', 'LSIL', "Past darajali leziya"],
      ['Yassi hujayra', 'HSIL', "Yuqori darajali leziya"], ['Yassi hujayra', 'SCC', "Yassi hujayrali rak"],
      ['Bez hujayra', 'AGC', "Atipik glandulyar hujayra"], ['Bez hujayra', 'AIS', "Adenokarsinoma in situ"],
    ],
    eslabQolish: "LSIL ko'pincha produktiv HPV infeksiyasi; HSIL transformatsion prekursor xavfi yuqori.",
    ehtiyot: "Boshqaruv faqat nomga emas, yosh, HPV genotipi va oldingi tarixga asoslangan ASCCP riskiga bog'liq.",
    manbalar: [{ nom: 'The Bethesda System 2014', url: 'https://link.springer.com/book/10.1007/978-3-319-11074-5' }],
  },
  {
    slug: 'figo-serviks-2018', nom: "Bachadon bo'yni saratoni FIGO",
    kategoriya: 'Onkoginekologiya', yangilanish: 'FIGO 2018',
    qisqa: "Servikal saraton tarqalishini I-IV bosqichga ajratadi; tasvirlash va patologiya natijasini qo'llashga ruxsat beradi.",
    tushuntirish: "I bosqich serviks bilan cheklangan. II bachadondan tashqariga chiqqan, ammo chanoq devori yoki pastki uch vagina emas. III pastki vagina, chanoq devori, gidronefroz yoki limfa tugunlari. IV qovuq/rektum shilliq qavati yoki uzoq metastaz.",
    qachon: "Biopsiya bilan tasdiqlangan servikal saratonda davolash va prognozni rejalashda.",
    ustunlar: ['Bosqich', 'Asosiy mezon'], qatorlar: [
      ['IA', 'Faqat mikroskopik invaziya; IA1 <3 mm, IA2 3-<5 mm'], ['IB', 'Serviksda, invaziya ≥5 mm; IB1 <2 sm, IB2 2-<4 sm, IB3 ≥4 sm'],
      ['II', 'Bachadondan tashqari; IIA parametraysiz, IIB parametrial invaziya'], ['III', 'Pastki 1/3 vagina, chanoq devori, buyrak oqimi yoki tugunlar'],
      ['IIIC1', 'Chanoq limfa tugunlari'], ['IIIC2', 'Para-aortal limfa tugunlari'], ['IVA', "Qovuq yoki rektum shilliq qavatiga o'sgan"], ['IVB', 'Uzoq metastaz'],
    ],
    eslabQolish: "2018 yangiligining ikki belgisi: IB o'lcham bo'yicha uchga bo'lindi va tugun metastazi IIIC bo'ldi.",
    ehtiyot: "r patologiya, p tasvirlash belgisi bilan bosqich manbasi ko'rsatiladi. Bullioz shishning o'zi IVA emas.",
    manbalar: [{ nom: 'Revised FIGO staging of cervical cancer 2018', url: 'https://doi.org/10.3802/jgo.2019.30.e40' }],
  },
  {
    slug: 'figo-endometrium-2023', nom: 'Endometrium saratoni FIGO',
    kategoriya: 'Onkoginekologiya', yangilanish: 'FIGO 2023',
    qisqa: "Endometrial saratonni anatomik tarqalish bilan birga gistologik agressivlik, LVSI va molekulyar turga mos bosqichlaydi.",
    tushuntirish: "2023 tizim eski 2009 tasnifidan ancha murakkab. I-II bosqichlarda o'smaning agressiv yoki noagressiv gistologiyasi va limfovaskulyar invaziya muhim. Molekulyar POLEmut va p53abn natijani bosqich yozuviga o'zgartiruvchi qo'shimcha beradi.",
    qachon: "Endometrial saraton operatsion patologiyasi va molekulyar natijalarini yakuniy bosqichlashda.",
    ustunlar: ['Bosqich', 'Talabaga asosiy mazmun'], qatorlar: [
      ['I', 'Bachadon tanasi bilan cheklangan; gistologiya va miometrial invaziyaga qarab IA1-IA3, IB, IC'],
      ['II', 'Servikal stroma, sezilarli LVSI yoki agressiv gistologiyada miometrial invaziya'],
      ['III', "Mahalliy yoki regional tarqalish: seroza/adneksa, vagina/parametriy, chanoq to'qimasi yoki tugunlar"],
      ['IV', "Qovuq/ichak shilliq qavati, qorin pardasi yoki uzoq metastaz"],
      ['IAmPOLEmut', "Erta POLE-mutatsiyali o'sma; molekulyar modifikatsiya"], ['IICmp53abn', "Erta p53-abnormal o'sma; yuqoriroq xavf modifikatsiyasi"],
    ],
    eslabQolish: "2023 FIGO faqat qayerga tarqalganini emas, o'smaning biologiyasini ham bosqichga qo'shadi.",
    ehtiyot: "To'liq subbosqich patologik va molekulyar ma'lumotsiz berilmaydi. Eski 2009 jadvali bilan aralashtirmang.",
    manbalar: [{ nom: 'FIGO staging of endometrial cancer 2023', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10482588/' }],
  },
  {
    slug: 'figo-tuxumdon-2014', nom: 'Tuxumdon nay va peritoneal saraton FIGO',
    kategoriya: 'Onkoginekologiya', yangilanish: 'FIGO 2014 amaldagi tizim',
    qisqa: "Tuxumdon, bachadon nayi va birlamchi peritoneal saratonni yagona I-IV tizimda bosqichlaydi.",
    tushuntirish: "I bosqich tuxumdon yoki nay bilan cheklangan. II kichik chanoq ichiga tarqalgan. III chanoqdan tashqari peritoneal yoki retroperitoneal tugun metastazi. IV uzoq metastaz.",
    qachon: "Onkoginekologik operatsiya, gistologiya va tasvirlash natijalarini yakuniy bosqichlashda.",
    ustunlar: ['Bosqich', 'Asosiy tarqalish'], qatorlar: [
      ['I', 'Tuxumdon yoki nay bilan cheklangan'], ['IC1', 'Operatsiya vaqtida kapsula yorilishi'], ['IC2', "Operatsiyadan oldin yorilish yoki yuzada o'sma"], ['IC3', 'Ascit/yuvindida malign hujayra'],
      ['II', 'Kichik chanoq ichidagi tarqalish'], ['III', 'Chanoqdan tashqari peritoneum va/yoki retroperitoneal tugun'], ['IVA', 'Plevral suyuqlikda malign hujayra'], ['IVB', 'Parenximatoz yoki chanoqdan tashqari tugun metastazi'],
    ],
    eslabQolish: "III peritoneal/retroperitoneal, IV esa haqiqiy uzoq metastaz.",
    ehtiyot: "Omentum metastazi ko'pincha III bosqich; jigar kapsulasi III, jigar parenximasi IVB.",
    manbalar: [{ nom: 'FIGO staging ovarian fallopian tube peritoneal cancer', url: 'https://doi.org/10.1016/j.ijgo.2014.04.001' }],
  },
  {
    slug: 'figo-vulva-2021', nom: 'Vulva saratoni FIGO',
    kategoriya: 'Onkoginekologiya', yangilanish: 'FIGO 2021',
    qisqa: "Vulva saratonini o'sma o'lchami, invaziya, qo'shni tuzilma va limfa tugunlariga qarab bosqichlaydi.",
    tushuntirish: "2021 tahriri prospektiv ma'lumotlar asosida soddalashtirilgan. Invaziya chuqurligi yangi usulda o'lchanadi va tasvirlash natijalari ham bosqichga kiritilishi mumkin.",
    qachon: "Vulva karsinomasi davolash hajmi va tugun taktikasini rejalashda; melanoma bundan mustasno.",
    ustunlar: ['Bosqich', 'Asosiy mezon'], qatorlar: [
      ['I', 'Vulva bilan cheklangan'], ['IA', "≤2 sm va stromal invaziya ≤1 mm"], ['IB', ">2 sm yoki invaziya >1 mm"],
      ['II', 'Pastki uretra/vagina/anusga tarqalgan, tugun manfiy'], ['III', 'Regional limfa tuguni metastazi'], ['IVA', "Yuqori uretra/vagina, qovuq/rektum yoki chanoq suyagiga fiksatsiya"], ['IVB', 'Uzoq metastaz'],
    ],
    eslabQolish: "I vulvada, II yaqin perineal tuzilmada, III tugunda, IV yuqori/uzoq tarqalishda.",
    ehtiyot: "Vulva melanomasi bu FIGO tizimi bilan emas, melanoma TNM tizimi bilan bosqichlanadi.",
    manbalar: [{ nom: 'FIGO vulvar cancer staging 2021', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9290586/' }],
  },
  {
    slug: 'gestatsion-trofoblastik-neoplaziya', nom: 'GTN FIGO va WHO xavf skori',
    kategoriya: 'Onkoginekologiya', yangilanish: 'FIGO amaldagi tizimi',
    qisqa: "Gestatsion trofoblastik neoplaziyada anatomik bosqich va kimyoterapiya rezistentligi xavfini birga yozadi.",
    tushuntirish: "FIGO I-IV kasallik tarqalishini bildiradi. Modifikatsiyalangan WHO skori yosh, oldingi homiladorlik, interval, hCG, o'sma, metastaz va oldingi dori haqidagi ballarni jamlaydi.",
    qachon: "Molyar homiladorlikdan keyingi GTN yoki xoriokarsinomada davolash rejimini tanlashda.",
    ustunlar: ['Qism', 'Daraja', 'Mazmuni'], qatorlar: [
      ['FIGO', 'I', 'Bachadon bilan cheklangan'], ['FIGO', 'II', 'Jinsiy aʼzolarga tarqalgan'], ['FIGO', 'III', "O'pka metastazi"], ['FIGO', 'IV', 'Boshqa uzoq metastaz'],
      ['WHO skor', '0-6', 'Past xavf'], ['WHO skor', '≥7', 'Yuqori xavf'], ['WHO skor', '≥13', "Juda yuqori xavf; ayrim qo'llanmalarda alohida e'tibor"],
    ],
    eslabQolish: "Natija masalan II:5 yoki III:8 ko'rinishida bosqich va skor bilan birga yoziladi.",
    ehtiyot: "PSTT va ETTda WHO skor odatiy GTN kabi davolash tanlamaydi. hCG dinamikasi va markaz protokoli muhim.",
    manbalar: [{ nom: 'FIGO Cancer Report gestational trophoblastic disease update', url: 'https://doi.org/10.1002/ijgo.13877' }],
  },
  {
    slug: 'orads-us-2022', nom: 'O RADS US', toliq: 'Ovarian Adnexal Reporting and Data System Ultrasound',
    kategoriya: 'Onkoginekologiya', yangilanish: 'ACR O-RADS US v2022',
    qisqa: "Adneksal hosilani UTT belgilariga ko'ra 0-5 xavf toifasiga ajratadi va boshqaruv tavsiyasini standartlashtiradi.",
    tushuntirish: "Tizim leziya turi, devor, lokula, solid komponent, papillyar proyeksiya va qon oqimini tahlil qiladi. Oddiy fiziologik topilma bilan yuqori malignlik xavfini bir xil tilda ajratadi.",
    qachon: "Adneksal massa UTT xulosasini standart yozish va kuzatuv/ekspert/onkolog yo'nalishini tanlashda.",
    ustunlar: ['Toifa', 'Maʼnosi', "Umumiy yo'nalish"], qatorlar: [
      ['0', "To'liq bo'lmagan tekshiruv", 'Takroriy yoki boshqa tasvirlash'], ['1', 'Normal tuxumdon', "Kuzatuv yo'q"], ['2', 'Deyarli aniq benign', "Ko'pincha kuzatuv yoki hech narsa"],
      ['3', 'Past xavf', 'UTT mutaxassisi yoki kuzatuv'], ['4', "O'rta xavf", 'Onkoginekologik maslahat'], ['5', 'Yuqori xavf', 'Onkoginekologik boshqaruv'],
    ],
    eslabQolish: "0 yetarli emas, 1 normal, 2 benign, 3 past, 4 o'rta, 5 yuqori xavf.",
    ehtiyot: "Aniq kategoriya to'liq O-RADS leksikoni va leziya o'lchamiga bog'liq. Homiladorlik va simptomli shoshilinch holatda boshqaruv o'zgaradi.",
    manbalar: [{ nom: 'ACR O-RADS US v2022', url: 'https://www.acr.org/Clinical-Resources/Reporting-and-Data-Systems/O-RADS' }],
  },
  {
    slug: 'pop-q', nom: 'POP Q prolaps tasnifi',
    kategoriya: 'Uroginekologiya', yangilanish: 'ICS IUGA amaldagi standart',
    qisqa: "Tos a'zolari prolapsini gimen tekisligiga nisbatan santimetrli o'lchov bilan 0-IV bosqichga ajratadi.",
    tushuntirish: "Aa, Ba old devor; Ap, Bp orqa devor; C serviks yoki vaginal cho'qqi; D orqa gumbaz. Musbat son gimen tashqarisiga, manfiy son ichkariga joylashuvni bildiradi.",
    qachon: "Prolapsni ko'rikda standart qayd etish, davolashdan oldin-keyin solishtirishda.",
    ustunlar: ['Bosqich', 'Eng distal nuqta'], qatorlar: [
      ['0', "Prolaps yo'q"], ['I', "Gimendan 1 sm dan ko'proq yuqorida"], ['II', 'Gimendan -1 sm dan +1 sm gacha'],
      ['III', 'Gimendan >1 sm pastda, ammo TVL-2 sm dan kam'], ['IV', "TVL-2 sm yoki undan ko'p; deyarli to'liq eversiya"],
    ],
    eslabQolish: "II bosqich gimen atrofidagi -1 dan +1 sm gacha bo'lgan zona.",
    ehtiyot: "Bosqich simptom kuchini to'liq aks ettirmaydi. Maksimal Valsalva va to'g'ri TVL o'lchovi kerak.",
    manbalar: [{ nom: 'ICS IUGA terminology for female pelvic floor dysfunction', url: 'https://doi.org/10.1007/s00192-009-0976-9' }],
  },
  {
    slug: 'robson-10-guruh', nom: 'Robson 10 guruh tasnifi',
    kategoriya: 'Akusherlik', yangilanish: 'WHO global standart',
    qisqa: "Barcha tug'ruq qiluvchi ayollarni kesarcha kesish ko'rsatkichlarini taqqoslash uchun o'zaro istisno qiluvchi 10 guruhga ajratadi.",
    tushuntirish: "Guruhlar paritet, oldingi kesarcha, homila soni, prezentatsiya, gestatsion yosh va tug'ruq boshlanishi bilan aniqlanadi. Bu individual ayolga kesarcha kerakligini hisoblamaydi; muassasa amaliyotini audit qiladi.",
    qachon: "Tug'ruqxona yoki hududda kesarcha kesish ulushini tahlil qilishda.",
    ustunlar: ['Guruh', 'Kim kiradi'], qatorlar: [
      ['1', "Nullipara, bitta bosh, ≥37 hafta, spontan tug'ruq"], ['2', 'Xuddi shu, induksiya yoki tugʻruqqacha kesarcha'],
      ['3', "Multipara, chandiqsiz, bitta bosh, ≥37 hafta, spontan"], ['4', 'Xuddi shu, induksiya yoki tugʻruqqacha kesarcha'],
      ['5', "Oldingi kesarcha, bitta bosh, ≥37 hafta"], ['6', 'Nullipara, chanoq prezentatsiyasi'], ['7', 'Multipara, chanoq prezentatsiyasi'],
      ['8', "Ko'p homila"], ['9', "Ko'ndalang yoki qiyshiq yotish"], ['10', 'Bitta bosh, <37 hafta'],
    ],
    eslabQolish: "1-4 muddatidagi bosh prezentatsiya; 5 chandiq; 6-7 chanoq; 8 ko'p; 9 ko'ndalang; 10 preterm.",
    ehtiyot: "Robson guruhi kesarcha uchun klinik ko'rsatma emas. Guruh hajmi va guruh ichidagi kesarcha ulushi birga tahlil qilinadi.",
    manbalar: [{ nom: 'WHO Robson Classification Implementation Manual', url: 'https://www.who.int/publications/i/item/9789241513197' }],
  },
  {
    slug: 'figo-ctg-2015', nom: 'FIGO intrapartum CTG tasnifi',
    kategoriya: 'Akusherlik', yangilanish: 'FIGO 2015 amaldagi konsensus',
    qisqa: "Bazal yurak urishi, variabellik va detseleratsiyalar bo'yicha CTGni normal, shubhali yoki patologik deb ajratadi.",
    tushuntirish: "CTG homilaning gipoksiya xavfini vaqt bo'yicha kuzatadi. Bitta belgi emas, uch asosiy komponent va klinik vaziyat birga baholanadi.",
    qachon: "Tug'ruq vaqtida elektron fetal monitoringni standart talqin qilishda.",
    ustunlar: ['Toifa', 'Sodda mezon'], qatorlar: [
      ['Normal', "Bazal 110-160; variabellik 5-25; takroriy kech yoki cho'zilgan detseleratsiya yo'q"],
      ['Shubhali', "Uch mezondan bittasi normalga mos emas, patologik mezon yo'q"],
      ['Patologik', 'Bazal <100; variabellik pasayishi/oshishi belgilangan muddatda; takroriy kech/uzoq detseleratsiya yoki sinusoidal pattern'],
    ],
    eslabQolish: "Normalda hammasi yaxshi; shubhalida bitta og'ish; patologikda aniq xavf belgisi.",
    ehtiyot: "CTGni alohida skrinshotdan emas, trend, qisqarishlar, dori, isitma va tug'ruq bosqichi bilan talqin qilish kerak.",
    manbalar: [{ nom: 'FIGO consensus guidelines on intrapartum fetal monitoring 2015', url: 'https://doi.org/10.1016/j.ijgo.2015.06.020' }],
  },
  {
    slug: 'perineal-yirtilish', nom: 'Perineal yirtilish darajalari',
    kategoriya: 'Akusherlik', yangilanish: 'RCOG OASI amaldagi tasnifi',
    qisqa: "Tug'ruqdagi perineal shikastni teridan anal sfinkter va rektal shilliq qavatgacha I-IV darajalaydi.",
    tushuntirish: "I-II darajalar anal sfinkterga yetmaydi. III daraja tashqi va ichki anal sfinkter shikastiga qarab a-c ga bo'linadi. IV darajada anorektal shilliq qavat ham yirtiladi.",
    qachon: "Vaginal tug'ruqdan keyin perineumni tekshirish, tikish va kuzatuv rejasida.",
    ustunlar: ['Daraja', "Shikastlangan to'qima"], qatorlar: [
      ['I', 'Faqat teri yoki vaginal epiteliy'], ['II', 'Perineal mushak, anal sfinkter butun'], ['IIIa', 'Tashqi sfinkterning <50% qalinligi'],
      ['IIIb', 'Tashqi sfinkterning ≥50% qalinligi'], ['IIIc', 'Tashqi va ichki anal sfinkter'], ['IV', 'Sfinkter kompleksi va anorektal shilliq qavat'],
    ],
    eslabQolish: "III sfinkter, IV sfinkter bilan birga rektal shilliq qavat.",
    ehtiyot: "Tugma teshik shikasti sfinkter butun bo'lsa ham alohida jiddiy jarohat; tajribali mutaxassis ko'rigi kerak.",
    manbalar: [{ nom: 'RCOG Green-top Guideline 29 OASI', url: 'https://www.rcog.org.uk/guidance/browse-all-guidance/green-top-guidelines/the-management-of-third-and-fourth-degree-perineal-tears-green-top-guideline-no-29/' }],
  },
  {
    slug: 'gipertenziv-buzilishlar', nom: 'Homiladorlikdagi gipertenziv buzilishlar',
    kategoriya: 'Akusherlik', yangilanish: 'ISSHP 2021',
    qisqa: "Homiladorlikdagi yuqori qon bosimini surunkali, gestatsion gipertenziya, preeklampsiya va oq xalat/maskalangan turlarga ajratadi.",
    tushuntirish: "20 haftadan oldin mavjud gipertenziya odatda surunkali. 20 haftadan keyin yangi gipertenziya gestatsion bo'lishi mumkin; proteinuriya yoki ona a'zolari/uteroplatsentar disfunksiya qo'shilsa preeklampsiya hisoblanadi.",
    qachon: "Antenatal qon bosimi oshganda tashxisni standart yozish va kuzatuv yo'nalishini tanlashda.",
    ustunlar: ['Toifa', 'Asosiy farqi'], qatorlar: [
      ['Surunkali gipertenziya', 'Homiladorlikdan oldin yoki <20 haftada mavjud'], ['Gestatsion gipertenziya', '≥20 haftada yangi, preeklampsiya belgisisiz'],
      ['Preeklampsiya', 'Yangi gipertenziya va proteinuriya yoki aʼzo/uteroplatsentar disfunksiya'], ['Surunkali fonida preeklampsiya', 'Surunkali gipertenziyaga yangi preeklampsiya belgisi qoʻshiladi'],
      ['Oq xalat', 'Klinikada yuqori, uy/ambulatory normal'], ['Maskalangan', 'Klinikada normal, uy/ambulatory yuqori'],
    ],
    eslabQolish: "Preeklampsiya uchun proteinuriya majburiy emas; boshqa a'zo yoki uteroplatsentar disfunksiya yetarli bo'lishi mumkin.",
    ehtiyot: "Og'ir qon bosimi va nevrologik, epigastral yoki nafas simptomlari shoshilinch bahoni talab qiladi; jadval yordam kutishni oqlamaydi.",
    manbalar: [{ nom: 'ISSHP recommendations 2021', url: 'https://doi.org/10.1161/HYPERTENSIONAHA.121.17550' }],
  },
  {
    slug: 'preterm-tugruq', nom: "Muddatidan oldin tug'ilish WHO",
    kategoriya: 'Akusherlik', yangilanish: 'WHO amaldagi taʼrif',
    qisqa: "37 hafta tugamasidan oldingi tirik tug'ilishni gestatsion yosh bo'yicha uch guruhga ajratadi.",
    tushuntirish: "Gestatsion yosh kichiklashgan sari nafas, harorat, ovqatlanish va nevrologik asoratlar xavfi oshadi. Guruhlar perinatal natijalarni taqqoslashga yordam beradi.",
    qachon: "Tug'ilish muddatini standart yozish, neonatal resurs va statistik hisobotda.",
    ustunlar: ['Guruh', 'Gestatsion yosh'], qatorlar: [
      ['Ekstremal preterm', '<28 hafta'], ['Juda preterm', '28 hafta - <32 hafta'], ['Oʻrta-kech preterm', '32 hafta - <37 hafta'], ['Muddatida', '37 hafta 0 kundan boshlab'],
    ],
    eslabQolish: "Asosiy chegaralar 28, 32 va 37 hafta.",
    ehtiyot: "Gestatsion yosh eng yaxshi obstetrik bahoga asoslanadi. Tug'ilgan vazn gestatsion yoshning o'rnini bosmaydi.",
    manbalar: [{ nom: 'WHO Preterm birth fact sheet', url: 'https://www.who.int/news-room/fact-sheets/detail/preterm-birth' }],
  },
  {
    slug: 'fgr-isuog', nom: "Homila o'sishdan ortda qolishi ISUOG", toliq: 'SGA va FGR farqi',
    kategoriya: 'Akusherlik', yangilanish: 'ISUOG 2020',
    qisqa: "Konstitutsional kichik SGA homilani patologik FGRdan biometrik va Doppler belgilar bilan ajratadi.",
    tushuntirish: "SGA odatda EFW yoki AC 10-percentildan pastligini bildiradi. FGR esa homila o'z o'sish potensialiga yetmayotgan patologik holat; juda kichik o'lcham, o'sishning pasayishi yoki Doppler buzilishi bilan aniqlanadi.",
    qachon: "Uchinchi trimestr UTTda kichik homila aniqlanganda monitoring va tug'ruq vaqtini rejalashda.",
    ustunlar: ['Toifa', 'Asosiy mazmun'], qatorlar: [
      ['SGA', "EFW yoki AC <10-percentil, lekin Doppler va o'sish dinamikasi normal bo'lishi mumkin"],
      ['Erta FGR', "<32 hafta; juda kichik o'lcham va/yoki kindik arteriyasi Doppler buzilishi"],
      ['Kech FGR', "≥32 hafta; o'lcham, percentilning tushishi va serebroplatsentar/uterin Doppler mezonlari kombinatsiyasi"],
    ],
    eslabQolish: "Har bir FGR kichik bo'lishi mumkin, lekin har bir SGA patologik FGR emas.",
    ehtiyot: "Aniq diagnostik mezon tanlangan o'sish standarti va protokolga bog'liq. Bitta UTTdan ko'ra trend va Doppler muhim.",
    manbalar: [{ nom: 'ISUOG Practice Guidelines SGA and FGR 2020', url: 'https://www.isuog.org/resource/isuog-practice-guidelines-diagnosis-and-management-of-sga-and-fgr.html' }],
  },
  {
    slug: 'placenta-previa', nom: 'Placenta previa va past joylashgan platsenta',
    kategoriya: 'Akusherlik', yangilanish: 'RCOG 2018 amaldagi terminlar',
    qisqa: "Platsentaning ichki servikal teshikka munosabatini previa yoki past joylashgan deb standart yozadi.",
    tushuntirish: "Eski I-IV darajali previa atamalari o'rniga UTTdagi aniq masofa ishlatiladi. Platsenta ichki teshikni yopsa previa, cheti teshikdan 20 mm ichida bo'lsa low-lying deyiladi.",
    qachon: "Ikkinchi va uchinchi trimestr UTTda platsenta past ko'ringanda kuzatuv va tug'ruq yo'lini rejalashda.",
    ustunlar: ['Toifa', 'Transvaginal UTT mezoni'], qatorlar: [
      ['Placenta previa', 'Platsenta ichki servikal teshikni yopadi'], ['Past joylashgan platsenta', 'Cheti ichki teshikdan <20 mm'], ['Normal joylashuv', 'Cheti ichki teshikdan ≥20 mm'],
    ],
    eslabQolish: "Yopsa previa; yopmay, 20 mm ichida bo'lsa low-lying.",
    ehtiyot: "Transvaginal UTT xavfsiz va aniq usul. Qon ketayotgan bemorda avval klinik barqarorlik; raqamli vaginal tekshiruv previa chiqarilmaguncha xavfli.",
    manbalar: [{ nom: 'RCOG Green-top Guideline 27a Placenta Praevia 2018', url: 'https://www.rcog.org.uk/guidance/browse-all-guidance/green-top-guidelines/placenta-praevia-and-placenta-accreta-diagnosis-and-management-green-top-guideline-no-27a/' }],
  },
]

export function ginKlassifikatsiyaTop(slug: string) {
  return GINEKOLOGIYA_KLASSIFIKATSIYALARI.find((item) => item.slug === slug)
}
