/**
 * Ginekologiya kalkulyatorlari uchun klinik kontent.
 *
 * UI ga ulangan: GinekologiyaKalkulyatorQobiq dagi KalkulyatorKontent (jonli
 * sahifalar ostida) va KalkulyatorInfoSahifa (ma'lumot sahifalari) slug
 * bo'yicha shu yerdan o'qiydi.
 *
 * Muhim: klinik qaror faqat kalkulyator natijasiga asoslanmasligi kerak.
 * Mahalliy protokol, bemorning holati va mutaxassis bahosi ustun turadi.
 */

export type KalkulyatorKontenti = {
  slug: string
  nomi: string
  kategoriya: string
  qisqaIzoh: string
  batafsilIzoh: string
  maydonlar: string[]
  hisoblash: string[]
  natijaTalqini: string[]
  cheklovlar: string[]
  manbalar: string[]
  // 5-qismli klinik izoh standartining qo'shimcha qismlari (ixtiyoriy —
  // bosqichma-bosqich to'ldiriladi):
  buNimaEmas?: string[]
  keyingiQadam?: string[]
  klinikMisol?: { vaziyat: string; javob: string }
  kopUchraydiganXato?: string[]
}

export const GINEKOLOGIYA_KALKULYATORLARI_KONTENTI: KalkulyatorKontenti[] = [
  {
    slug: 'homiladorlik-muddati',
    nomi: "Homiladorlik muddati va taxminiy tug'ruq sanasi",
    kategoriya: 'Homiladorlik',
    qisqaIzoh: "Oxirgi hayzning birinchi kuni asosida akusherlik gestatsion yoshi va taxminiy tug'ruq sanasini hisoblaydi.",
    batafsilIzoh: "Akusherlikda homiladorlik muddati urug'lanish kunidan emas, oxirgi hayzning birinchi kunidan sanaladi. Shu sabab gestatsion yosh embrion yoshidan odatda taxminan 2 hafta katta. Masalan, oxirgi hayz 7-avgustda boshlangan va ovulyatsiya 20-21-avgustda bo'lgan bo'lsa, 8-sentabrda gestatsion yosh 4 hafta 4 kun, embrion yoshi esa taxminan 2 hafta 4-5 kun bo'ladi. Ikkala natija ham o'z hisob tizimida to'g'ri, ammo tibbiy hujjatlarda gestatsion yosh ishlatiladi.",
    maydonlar: ["Oxirgi hayzning birinchi kuni", "Odatdagi sikl uzunligi, 21-35 kun", "Baholash sanasi"],
    hisoblash: [
      "28 kunlik siklda taxminiy tug'ruq sanasi = oxirgi hayzning birinchi kuni + 280 kun.",
      "Sikl 28 kundan farq qilsa, taxminiy tug'ruq sanasiga sikl uzunligi - 28 kun tuzatishi qo'shiladi.",
      "Gestatsion yosh = baholash sanasi - oxirgi hayz sanasi - sikl tuzatishi.",
      "Taxminiy embrion yoshi = gestatsion yosh - 14 kun. Bu faqat taxminiy ko'rsatkich sifatida alohida chiqarilishi mumkin.",
    ],
    natijaTalqini: ["Asosiy natija hafta + kun ko'rinishida beriladi.", "Taxminiy tug'ruq sanasi alohida ko'rsatiladi.", "Natija yonida gestatsion va embrion yoshining farqi tushuntiriladi."],
    cheklovlar: ["Hayz sanasi noma'lum yoki sikl notekis bo'lsa aniqlik pasayadi.", "ART/IVF homiladorlikda embrion ko'chirilgan sana va embrion yoshi ishlatiladi.", "Birinchi trimestrdagi sifatli UTT sanalashi ko'pincha ishonchliroq."],
    manbalar: ["ACOG Committee Opinion 700 Methods for Estimating the Due Date", "AIUM va SMFM homiladorlikni sanalash tavsiyalari"],
    buNimaEmas: [
      "Homiladorlik borligini tasdiqlamaydi — buni test/UTT aniqlaydi.",
      "Aniq tug'ruq kunini kafolatlamaydi — TTS atrofida ±2 hafta normal.",
      "Embrionning haqiqiy yoshini bermaydi (u ~2 hafta kam).",
    ],
    keyingiQadam: [
      "Birinchi trimestr UTT (CRL) bilan muddatni tasdiqlang.",
      "Hayz noma'lum yoki sikl notekis bo'lsa, UTT sanasiga tayaning.",
      "ART/IVF bo'lsa embrion ko'chirish sanasidan hisoblang.",
    ],
    klinikMisol: {
      vaziyat: "OHS 7-avgust, 28 kunlik sikl, bugun 8-sentabr.",
      javob: "Gestatsion muddat 4 hafta 4 kun, TTS ~14-may. Embrionning haqiqiy yoshi esa ~2 hafta 4 kun — hujjatga gestatsion muddat yoziladi.",
    },
    kopUchraydiganXato: [
      "Gestatsion muddatni embrion yoshi bilan aralashtirish.",
      "Notekis siklda kalendarga ishonib, UTT sanasini e'tiborsiz qoldirish.",
    ],
  },
  {
    slug: 'gestatsion-yosh-utt',
    nomi: "UTT bo'yicha gestatsion yosh",
    kategoriya: 'Homiladorlik',
    qisqaIzoh: "Birinchi trimestrda CRL o'lchami asosida gestatsion yoshni baholaydi.",
    batafsilIzoh: "CRL bosh-dumg'aza uzunligidir. Birinchi trimestrda homiladorlik yoshini aniqlash uchun eng aniq biometrik o'lchov hisoblanadi. O'lchov haqiqiy midsagittal kesimda olinishi va imkon qadar uchta to'g'ri o'lchovning o'rtachasi ishlatilishi kerak.",
    maydonlar: ["CRL, millimetr", "UTT o'tkazilgan sana"],
    hisoblash: ["INTERGROWTH-21st: GA kun = 40.9041 + 3.21585 x sqrt(CRL) + 0.348956 x CRL.", "Hafta = GA kun / 7 ning butun qismi; qolgan kun = GA kun mod 7.", "Taxminiy tug'ruq sanasi = UTT sanasi + 280 - GA kun."],
    natijaTalqini: ["Natija hafta + kun ko'rinishida beriladi.", "Birinchi trimestrda odatiy aniqlik taxminan +/-5-7 kun."],
    cheklovlar: ["Formula asosan 9 hafta 0 kundan 13 hafta 6 kungacha validatsiya qilingan.", "CRL 84 mm dan oshganda kompozit ikkinchi trimestr biometriyasi afzal.", "Keyingi UTTlarda o'sish farqi sabab tug'ruq sanasini odatda qayta o'zgartirmaslik kerak."],
    manbalar: ["Papageorghiou va boshqalar INTERGROWTH-21st CRL dating standard 2014", "ACOG Committee Opinion 700"],
    buNimaEmas: [
      "Homila sog'lig'ini yoki nuqsonni baholamaydi — bu alohida UTT vazifasi.",
      "13 hafta 6 kundan keyin ishonchli emas (CRL 84 mm dan oshganda).",
      "Keyingi UTTlarda o'sish farqi bo'lsa ham TTS ni odatda qayta o'zgartirmaydi.",
    ],
    keyingiQadam: [
      "CRL to'g'ri midsagittal kesimda, 3 o'lchov o'rtachasida olinsin.",
      "CRL 84 mm dan katta bo'lsa ikkinchi trimestr biometriyasiga o'ting.",
      "Muddatni birinchi ishonchli UTTga qarab belgilang va keyin saqlang.",
    ],
    klinikMisol: {
      vaziyat: "CRL 45 mm, UTT bugun o'tkazildi.",
      javob: "Gestatsion yosh ~11 hafta 1 kun. Bu OHS bo'yicha hisobdan ishonchliroq — muddat shunga ko'ra belgilanadi.",
    },
    kopUchraydiganXato: [
      "CRL 84 mm dan oshganda ham CRL formulasiga tayanish.",
      "Har bir keyingi UTTda TTS ni qayta hisoblab o'zgartirish.",
    ],
  },
  {
    slug: 'homila-vazni',
    nomi: 'Homilaning taxminiy vazni Hadlock',
    kategoriya: 'Homiladorlik',
    qisqaIzoh: "UTT biometrik o'lchamlari asosida homilaning taxminiy vaznini hisoblaydi.",
    batafsilIzoh: "Hadlock IV modeli BPD, HC, AC va FL o'lchamlarini birlashtiradi. Natija homilaning o'sishini gestatsion yoshga mos percentillar bilan baholash va ketma-ket UTTlarda o'sish dinamikasini kuzatish uchun ishlatiladi.",
    maydonlar: ["BPD biparietal diametr, mm", "HC bosh aylanasi, mm", "AC qorin aylanasi, mm", "FL son suyagi uzunligi, mm"],
    hisoblash: ["Avval barcha o'lchamlar mm dan sm ga o'tkaziladi.", "log10 EFW = 1.3596 + 0.0064xHC + 0.0424xAC + 0.174xFL + 0.00061xBPDxAC - 0.00386xACxFL.", "EFW gramm = 10 darajasi log10 EFW."],
    natijaTalqini: ["Natija gramm va kilogrammda ko'rsatiladi.", "Yonida taxminiy +/-10 foizlik diapazon berilishi mumkin.", "Gestatsion yosh ma'lum bo'lsa, percentil alohida standart jadval orqali aniqlanadi."],
    cheklovlar: ["Bu haqiqiy vazn emas; individual xatolik 10 foizdan katta bo'lishi mumkin.", "Noto'g'ri UTT kesimi yoki o'lchov xatosi natijaga kuchli ta'sir qiladi.", "Percentil uchun bir xil tanlangan o'sish standarti izchil ishlatilishi kerak."],
    manbalar: ["Hadlock FP va boshqalar Am J Obstet Gynecol 1985", "ISUOG fetal biometry guidance"],
    buNimaEmas: [
      "Haqiqiy tug'ilish vaznini bermaydi — xatolik ±10% va undan ko'p bo'lishi mumkin.",
      "Makrosomiya yoki FGR tashxisini yakka o'zi qo'ymaydi.",
      "Gestatsion yoshsiz percentilni aniqlamaydi.",
    ],
    keyingiQadam: [
      "Gestatsion yoshga mos percentil bilan o'sishni baholang.",
      "Bitta o'lchovga emas, ketma-ket UTT dinamikasiga qarang.",
      "Doppler va suv miqdorini birga baholab, FGR/makrosomiyani ko'rib chiqing.",
    ],
    klinikMisol: {
      vaziyat: "BPD 90, HC 330, AC 350, FL 70 mm.",
      javob: "Taxminiy vazn ~3305 g (±10% ≈ 2975–3636 g). Bu — taxmin; qaror percentil va dinamika bilan chiqariladi.",
    },
    kopUchraydiganXato: [
      "Taxminiy vaznni haqiqiy vazndek qabul qilish.",
      "Bitta UTT asosida makrosomiya deb kesar rejalashtirish.",
    ],
  },
  {
    slug: 'bishop',
    nomi: 'Bishop shkalasi',
    kategoriya: "Tug'ruq",
    qisqaIzoh: "Bachadon bo'ynining tug'ruq induksiyasiga tayyorligini baholaydi.",
    batafsilIzoh: "Shkala bachadon bo'ynining ochilishi, qisqarishi yoki uzunligi, konsistensiyasi, holati va homila boshining stansiyasini baholaydi. U induksiya muvaffaqiyati ehtimolini taxmin qilishga yordam beradi, ammo induksiya kerak yoki kerak emasligini yakka o'zi hal qilmaydi.",
    maydonlar: ["Ochilish, sm", "Effacement foizi yoki serviks uzunligi", "Homila boshi stansiyasi", "Serviks konsistensiyasi", "Serviks holati"],
    hisoblash: ["Har bir belgi 0-2 yoki 0-3 ball bilan baholanadi.", "Klassik umumiy ball 0-13 oralig'ida."],
    natijaTalqini: ["8 va undan yuqori ball odatda yetilgan, induksiyaga qulay serviksni bildiradi.", "5 va undan past ball yetilmagan serviksga mos; servikal tayyorlash ko'rib chiqilishi mumkin."],
    cheklovlar: ["Baholovchilar orasida farq bo'lishi mumkin.", "Turli muassasalarda modifikatsiyalangan mezon va chegaralar ishlatiladi.", "Natija klinik ko'rsatma va qarshi ko'rsatmalar bilan birga talqin qilinadi."],
    manbalar: ["Bishop EH Obstet Gynecol 1964", "ACOG labor induction guidance"],
  },
  {
    slug: 'apgar',
    nomi: 'Apgar shkalasi',
    kategoriya: "Tug'ruq",
    qisqaIzoh: "Yangi tug'ilgan chaqaloqning tug'ilgandan keyingi holatini standart tarzda qayd etadi.",
    batafsilIzoh: "Apgar yurak urishi, nafas, mushak tonusi, reflektor javob va teri rangini baholaydi. Odatda 1 va 5-daqiqada, 5-daqiqa bali 7 dan past bo'lsa keyin har 5 daqiqada 20-daqiqagacha qayta baholanadi.",
    maydonlar: ["Appearance rang", "Pulse yurak urishi", "Grimace reflektor javob", "Activity mushak tonusi", "Respiration nafas"],
    hisoblash: ["Har bir komponent 0, 1 yoki 2 ball.", "Jami ball 0-10."],
    natijaTalqini: ["7-10 ball odatda yaxshi moslashuvga mos.", "4-6 ball o'rtacha buzilishni bildiradi.", "0-3 ball og'ir holatga mos va zudlik bilan reanimatsion baholashni talab qiladi."],
    cheklovlar: ["Reanimatsiyani boshlash uchun 1-daqiqa balini kutish mumkin emas.", "Apgar asfiksiya tashxisini yoki uzoq muddatli nevrologik prognozni yakka o'zi belgilamaydi.", "Prematurlik, dori va tug'ma nuqsonlar ballga ta'sir qiladi."],
    manbalar: ["ACOG Committee Opinion The Apgar Score", "American Academy of Pediatrics neonatal guidance"],
  },
  {
    slug: 'qon-yoqotish',
    nomi: "Tug'ruqdan keyingi qon yo'qotishni miqdoriy baholash",
    kategoriya: "Tug'ruq",
    qisqaIzoh: "Nam materiallar vazni va yig'ilgan suyuqlik hajmi bo'yicha umumiy qon yo'qotishni hisoblaydi.",
    batafsilIzoh: "Vizual baholash katta qon yo'qotishda hajmni kamaytirib ko'rsatishi mumkin. Miqdoriy usul nam va quruq material vazni farqini hamda kalibrlangan idishdagi qon hajmini jamlaydi.",
    maydonlar: ["Har bir nam material vazni, g", "Har bir quruq material vazni, g", "Yig'ilgan suyuqlik, ml", "Amniotik va irrigatsion suyuqlik, ml"],
    hisoblash: ["Materialdagi qon ml = nam vazn g - quruq vazn g; 1 g taxminan 1 ml.", "Jami qon = materiallardagi qon + idishdagi suyuqlik - qon bo'lmagan suyuqlik."],
    natijaTalqini: ["1000 ml yoki undan ko'p kumulyativ qon yo'qotish, yoxud hajmdan qat'i nazar gipovolemiya belgilari obstetrik qon ketish mezoniga mos."],
    cheklovlar: ["Hisob reanimatsiya va qon ketish sababini aniqlashni kechiktirmasligi kerak.", "Aralash suyuqliklar to'g'ri ayrilmasa natija xato bo'ladi.", "Bemorning gemodinamik holati raqamdan muhimroq bo'lishi mumkin."],
    manbalar: ["ACOG Committee Opinion 794 Quantitative Blood Loss in Obstetric Hemorrhage", "ACOG Practice Bulletin Postpartum Hemorrhage"],
  },
  {
    slug: 'vbac',
    nomi: 'VBAC muvaffaqiyat ehtimoli',
    kategoriya: "Tug'ruq",
    qisqaIzoh: "Oldingi kesarcha kesishdan keyin vaginal tug'ruq muvaffaqiyati ehtimolini taxmin qiladi.",
    batafsilIzoh: "Validatsiya qilingan model ona yoshi, BMI, oldingi vaginal tug'ruq, oldingi VBAC, kesarcha sababi va joriy klinik ma'lumotlardan foydalanadi. Natija umumiy qaror qabul qilishga yordam beradi; past hisoblangan ehtimolning o'zi TOLACni taqiqlamaydi.",
    maydonlar: ["Ona yoshi", "Homiladorlikdan oldingi BMI", "Oldingi vaginal tug'ruq", "Oldingi VBAC", "Oldingi kesarcha sababi", "Joriy gestatsion va obstetrik holat"],
    hisoblash: ["Faqat tanlangan, e'lon qilingan va maqsad populyatsiyada validatsiya qilingan model koeffitsiyentlari ishlatiladi.", "Irq yoki etnik mansublikni biologik koeffitsiyent sifatida ishlatmaydigan yangilangan model tanlanadi."],
    natijaTalqini: ["Natija foiz ko'rinishida taxminiy ehtimol sifatida beriladi.", "Bachadon yorilishi xavfi va shoshilinch kesarcha imkoniyati alohida muhokama qilinadi."],
    cheklovlar: ["Kalkulyator individual natijani kafolatlamaydi.", "TOLAC faqat shoshilinch kesarcha va monitoring imkoniyati bor muassasada rejalashtiriladi.", "Model past ehtimolli bemorni avtomatik rad etish uchun ishlatilmaydi."],
    manbalar: ["NICHD MFMU VBAC prediction model", "ACOG Practice Bulletin Vaginal Birth After Cesarean Delivery"],
  },
  {
    slug: 'preeklampsiya-xavfi',
    nomi: 'Preeklampsiya xavfini baholash',
    kategoriya: 'Homiladorlik',
    qisqaIzoh: "Ona anamnezi va mavjud bo'lsa biomarkerlar asosida preeklampsiya xavfini baholaydi.",
    batafsilIzoh: "Bu nom ostida ikki xil vosita bo'lishi mumkin: ACOG yoki NICE xavf omillari bo'yicha aspirin profilaktikasiga moslik tekshiruvi va FMF kabi individual ehtimol modeli. Ularni bitta natijaga aralashtirmaslik kerak.",
    maydonlar: ["Oldingi preeklampsiya", "Ko'p homilalik", "Surunkali gipertoniya", "Diabet", "Buyrak yoki autoimmun kasallik", "BMI, yosh va oilaviy anamnez", "Model talab qilsa MAP, UtA-PI va PlGF"],
    hisoblash: ["Xavf omillari rejimida yuqori va o'rtacha xavf omillari sanaladi.", "Individual model rejimida faqat litsenziyalangan va validatsiya qilingan algoritm ishlatiladi."],
    natijaTalqini: ["Natija skrining xavfi, tashxis emas.", "Profilaktika tavsiyasi mahalliy protokoldagi homiladorlik haftasi va qarshi ko'rsatmalar bilan birga chiqariladi."],
    cheklovlar: ["Qon bosimi va proteinuriya mavjud preeklampsiyani klinik baholashni talab qiladi.", "Biomarkerli modelning koeffitsiyentlarini manbasiz taxmin qilish mumkin emas."],
    manbalar: ["ACOG Practice Advisory Low Dose Aspirin Use", "NICE Hypertension in pregnancy", "Fetal Medicine Foundation preeclampsia screening"],
  },
  {
    slug: 'rcog-obstetrik-vte',
    nomi: 'Homiladorlik va puerperiyda VTE xavfi RCOG',
    kategoriya: 'Homiladorlik',
    qisqaIzoh: "Homiladorlik va tug'ruqdan keyingi davrda venoz tromboemboliya xavf omillarini ballaydi.",
    batafsilIzoh: "Platformadagi eski 'Padua obstetrik VTE' nomini ishlatmaslik kerak. Padua shkalasi umumiy hospitalizatsiyadagi tibbiy bemorlar uchun tuzilgan. Obstetrik modul uchun RCOG Green-top 37a dagi antenatal va postnatal xavf bahosi mos.",
    maydonlar: ["Oldingi VTE", "Trombofiliya", "Komorbid kasalliklar", "Yosh, BMI, paritet va chekish", "Obstetrik omillar", "Vaqtinchalik omillar", "Antenatal yoki postnatal bosqich", "Qon ketish xavfi"],
    hisoblash: ["Har bir RCOG omiliga 1-4 ball beriladi.", "Jami antenatal va postnatal kontekstda alohida talqin qilinadi."],
    natijaTalqini: ["Antenatal jami 4 yoki ko'p bo'lsa birinchi trimestrdan profilaktikani ko'rib chiqish.", "Antenatal jami 3 bo'lsa 28-haftadan profilaktikani ko'rib chiqish.", "Postnatal jami 2 yoki ko'p bo'lsa kamida 10 kun profilaktikani ko'rib chiqish."],
    cheklovlar: ["Oldingi VTE va ayrim trombofiliyalarda jami balldan qat'i nazar mutaxassis rejasi kerak.", "Qon ketish xavfi bo'lsa gematolog yoki tajribali akusher bilan foyda-xavf baholanadi.", "RCOG yangilanishlari kuzatib boriladi."],
    manbalar: ["RCOG Green-top Guideline 37a amended 2023 Appendix III"],
  },
  {
    slug: 'ferriman-gallwey',
    nomi: 'Modifikatsiyalangan Ferriman Gallwey shkalasi',
    kategoriya: 'Reproduktiv salomatlik',
    qisqaIzoh: "Ayollarda terminal tuklanish darajasini to'qqiz androgen-sezgir sohada baholaydi.",
    batafsilIzoh: "Har bir anatomik soha 0 dan 4 gacha baholanadi. Shkala girsutizm og'irligini standartlashtiradi va davolash dinamikasini kuzatishga yordam beradi.",
    maydonlar: ["Yuqori lab", "Iyak", "Ko'krak", "Yuqori va pastki qorin", "Yuqori va pastki orqa", "Qo'l", "Son"],
    hisoblash: ["To'qqiz soha ballari qo'shiladi; jami 0-36."],
    natijaTalqini: ["Ko'p populyatsiyalarda 8 va undan yuqori ball girsutizmga mos deb olinadi.", "Etnik populyatsiyaga mos chegara ishlatilishi kerak."],
    cheklovlar: ["Kosmetik tuk olib tashlash bahoni buzadi.", "Shkala biokimyoviy giperandrogenizm tashxisini qo'ymaydi.", "Fotosurat yoki chizmalarni litsenziyasiz ko'chirmaslik kerak."],
    manbalar: ["Ferriman va Gallwey JCEM 1961", "Endocrine Society Hirsutism Clinical Practice Guideline"],
  },
  {
    slug: 'free-androgen-index',
    nomi: 'Erkin androgen indeksi FAI',
    kategoriya: 'Reproduktiv salomatlik',
    qisqaIzoh: "Umumiy testosteron va SHBG orqali biologik faol androgen ulushini taxmin qiladi.",
    batafsilIzoh: "FAI ayollarda giperandrogenizmni baholashda yordamchi ko'rsatkich. Testosteron va SHBG bir xil molyar birlikda bo'lishi shart.",
    maydonlar: ["Umumiy testosteron, nmol/L", "SHBG, nmol/L"],
    hisoblash: ["FAI foiz = umumiy testosteron / SHBG x 100."],
    natijaTalqini: ["Natija laboratoriyaning ayollar uchun validatsiya qilingan referens intervali bilan solishtiriladi."],
    cheklovlar: ["Universallashgan bitta chegara yo'q; assay va laboratoriyaga bog'liq.", "SHBG juda past bo'lsa FAI erkin testosteronni ortiqcha baholashi mumkin.", "Homiladorlik va gormonal dorilar SHBGni o'zgartiradi."],
    manbalar: ["Society for Endocrinology androgen excess guidance", "Mahalliy laboratoriya assay referenslari"],
  },
  {
    slug: 'homa-ir',
    nomi: 'HOMA IR indeksi',
    kategoriya: 'Reproduktiv salomatlik',
    qisqaIzoh: "Och qoringa glyukoza va insulin orqali insulin rezistentligini taxmin qiladi.",
    batafsilIzoh: "HOMA-IR ko'pincha PCOS bo'yicha tadqiqotlarda metabolik holatni baholash uchun ishlatiladi. U diabet yoki gestatsion diabet tashxisini qo'ymaydi.",
    maydonlar: ["Och qoringa glyukoza, mmol/L yoki mg/dL", "Och qoringa insulin, uIU/mL"],
    hisoblash: ["mmol/L bo'lsa HOMA-IR = glyukoza x insulin / 22.5.", "mg/dL bo'lsa HOMA-IR = glyukoza x insulin / 405."],
    natijaTalqini: ["Natija laboratoriya va populyatsiyaga mos chegara bilan talqin qilinadi; universal cutoff yo'q."],
    cheklovlar: ["O'tkir kasallik, steroidlar va och qolmaslik natijani buzadi.", "Homiladorlikda fiziologik insulin rezistentligi oshadi.", "Klinik amaliyotda OGTT yoki standart glikemik mezonlarni almashtirmaydi."],
    manbalar: ["Matthews va boshqalar Diabetologia 1985 HOMA model", "International evidence based PCOS guideline"],
  },
  {
    slug: 'amh-yoshga-mos',
    nomi: 'AMH natijasini yoshga mos baholash',
    kategoriya: 'Reproduktiv salomatlik',
    qisqaIzoh: "AMH natijasini yosh va laboratoriya usuliga mos referens bilan taqqoslaydi.",
    batafsilIzoh: "AMH tuxumdon zaxirasining miqdoriy markeri va stimulyatsiyaga javobni taxmin qilishda foydali. U tabiiy homilador bo'lish imkonini yoki tuxum sifatini bevosita o'lchamaydi.",
    maydonlar: ["Yosh", "AMH qiymati", "Birlik ng/mL yoki pmol/L", "Assay yoki laboratoriya"],
    hisoblash: ["Birlik zarur bo'lsa 1 ng/mL taxminan 7.14 pmol/L orqali aylantiriladi.", "Natija tanlangan assayning yoshga xos percentil jadvali bilan solishtiriladi."],
    natijaTalqini: ["Past, yoshga mos yoki yuqori diapazon ko'rsatiladi.", "Yuqori AMH PCOS bilan uchrashi mumkin, ammo tashxis emas."],
    cheklovlar: ["Turli assay natijalari to'liq almashtirilmaydi.", "Kontratseptivlar va ayrim klinik holatlar AMHga ta'sir qilishi mumkin.", "Universal yosh formulasi mavjud emas; jadval manbasi UI da ko'rsatilishi shart."],
    manbalar: ["ASRM ovarian reserve testing committee opinion", "ESHRE ovarian stimulation guideline", "Ishlatiladigan assay ishlab chiqaruvchisi referenslari"],
  },
  {
    slug: 'ovulyatsiya-kuni',
    nomi: 'Ovulyatsiya kunini taxminlash',
    kategoriya: 'Reproduktiv salomatlik',
    qisqaIzoh: "Sikl sanalari asosida taxminiy ovulyatsiya va fertil oynani ko'rsatadi.",
    batafsilIzoh: "Ovulyatsiya har doim siklning 14-kuni emas. U ko'pincha keyingi hayzdan taxminan 14 kun oldin sodir bo'ladi. Fertil oyna ovulyatsiyadan oldingi 5 kun va ovulyatsiya kunini qamrab oladi.",
    maydonlar: ["Oxirgi hayzning birinchi kuni", "O'rtacha sikl uzunligi", "Sikl muntazamligi"],
    hisoblash: ["Keyingi hayz = OHS + sikl uzunligi.", "Taxminiy ovulyatsiya = keyingi hayz - 14 kun.", "Fertil oyna = ovulyatsiyadan 5 kun oldin boshlab ovulyatsiya kunigacha."],
    natijaTalqini: ["Bitta aniq kun emas, sana oralig'i ko'rsatiladi."],
    cheklovlar: ["Notekis sikl, laktatsiya, perimenopauza va PCOSda kalendar usuli ishonchsiz.", "Homiladorlikdan saqlanishning yakka usuli sifatida tavsiya qilinmaydi.", "LH testlari va follikulometriya aniqlikni oshiradi."],
    manbalar: ["ASRM Optimizing natural fertility committee opinion"],
  },
  {
    slug: 'menopauza-mrs',
    nomi: 'Menopauza reyting shkalasi MRS',
    kategoriya: 'Reproduktiv salomatlik',
    qisqaIzoh: "Menopauza bilan bog'liq 11 simptomning og'irligini va davolash dinamikasini baholaydi.",
    batafsilIzoh: "MRS simptomlarni somatovegetativ, psixologik va urogenital domenlarga ajratadi. Har bir savol 0 dan 4 gacha baholanadi.",
    maydonlar: ["MRSning litsenziya va tarjima talablari bajarilgan 11 savoliga javoblar"],
    hisoblash: ["Har bir javob 0-4 ball; jami 0-44.", "Domen ballari va umumiy ball alohida jamlanadi."],
    natijaTalqini: ["Yuqori ball simptomlar og'irroq ekanini bildiradi.", "Takroriy baholash davolashga javobni ko'rsatadi."],
    cheklovlar: ["Menopauza tashxisini yakka o'zi qo'ymaydi.", "Rasmiy yoki validatsiya qilingan o'zbekcha tarjima bo'lmasa savollarni erkin tarjima qilib klinik valid deb ko'rsatmaslik kerak."],
    manbalar: ["Menopause Rating Scale official manual", "Heinemann va boshqalar MRS validation publications"],
  },
  {
    slug: 'frax',
    nomi: 'FRAX osteoporotik sinish xavfi',
    kategoriya: 'Reproduktiv salomatlik',
    qisqaIzoh: "10 yillik katta osteoporotik va son bo'g'imi sinishi ehtimolini baholaydi.",
    batafsilIzoh: "FRAX klinik xavf omillari va ixtiyoriy femoral bo'yin BMD ko'rsatkichidan foydalanadi. Model mamlakatga xos bo'lib, aynan rasmiy FRAX algoritmi ishlatilishi kerak.",
    maydonlar: ["Mamlakat modeli", "Yosh va jins", "Vazn va bo'y", "Oldingi sinish", "Ota-onada son sinishi", "Chekish", "Glyukokortikoid", "Revmatoid artrit", "Ikkilamchi osteoporoz", "Alkogol", "Femoral bo'yin BMD yoki T-score"],
    hisoblash: ["Rasmiy FRAX API yoki litsenziyalangan algoritmsiz formulani taxminan qayta yaratmaslik kerak."],
    natijaTalqini: ["10 yillik katta osteoporotik sinish foizi.", "10 yillik son bo'g'imi sinishi foizi.", "Davolash chegarasi mahalliy qo'llanmaga bog'liq."],
    cheklovlar: ["Premenopauzal ayollar uchun odatiy vosita emas.", "Doza-javob va yiqilishlar kabi ayrim xavflarni to'liq hisobga olmaydi.", "FRAX nomi va algoritmi litsenziya talablariga ega."],
    manbalar: ["FRAX Sheffield official tool and terms", "Mahalliy osteoporoz klinik qo'llanmasi"],
  },
  {
    slug: 'rmi',
    nomi: "RMI tuxumdon o'smasi malignlik indeksi",
    kategoriya: 'Onkoginekologiya',
    qisqaIzoh: "UTT belgilarini, menopauzal holatni va CA-125 ni birlashtirib adneksal massaning malignlik xavfini baholaydi.",
    batafsilIzoh: "RMI I modeli beshta UTT belgisini sanaydi, menopauzal status koeffitsiyentini qo'llaydi va CA-125 bilan ko'paytiradi. Natija ginekologik onkologga yo'naltirishni rejalashda yordam beradi.",
    maydonlar: ["Multilokulyarlik", "Solid soha", "Ikki tomonlama massa", "Ascit", "Metastaz belgisi", "Premenopauza yoki postmenopauza", "CA-125 U/mL"],
    hisoblash: ["U = 0 belgi bo'lsa 0, 1 belgi bo'lsa 1, 2-5 belgi bo'lsa 3.", "M = premenopauza 1, postmenopauza 3.", "RMI I = U x M x CA-125."],
    natijaTalqini: ["Ko'p protokollarda 200 va undan yuqori yuqori xavf hisoblanadi va onkoginekologik yo'naltirishni qo'llab-quvvatlaydi."],
    cheklovlar: ["CA-125 endometrioz, yallig'lanish va hayzda ham ko'tarilishi mumkin.", "Erta bosqich va ayrim gistologik turlarda CA-125 normal bo'lishi mumkin.", "Mahalliy yo'naltirish cutoffi tekshiriladi."],
    manbalar: ["Jacobs va boshqalar Br J Obstet Gynaecol 1990", "NICE Ovarian cancer recognition and initial management"],
  },
  {
    slug: 'roma',
    nomi: 'ROMA tuxumdon malignligi xavfi algoritmi',
    kategoriya: 'Onkoginekologiya',
    qisqaIzoh: "HE4, CA-125 va menopauzal statusdan foydalanib adneksal massada malignlik xavfini baholaydi.",
    batafsilIzoh: "ROMA laborator biomarker algoritmi. Premenopauza va postmenopauza uchun turli prediktiv indeks tenglamalari ishlatiladi. U skrining testi emas va faqat operatsiya rejalashtirilayotgan adneksal massada yordamchi vosita sifatida qo'llanadi.",
    maydonlar: ["HE4", "CA-125", "Menopauzal status", "Ishlatilgan assay platformasi"],
    hisoblash: ["Koeffitsiyent va cutoff assay ishlab chiqaruvchisiga bog'liq.", "Dastur aynan tanlangan laborator platformaning validatsiya qilingan PI tenglamasi va chegarasini ishlatishi kerak."],
    natijaTalqini: ["Natija past yoki yuqori xavf sifatida assayga xos cutoff bo'yicha beriladi."],
    cheklovlar: ["Buyrak funksiyasi pasayganda HE4 ko'tarilishi mumkin.", "Tuxumdon saratoni skriningi uchun ishlatilmaydi.", "Assaylar o'rtasida formulani ko'chirish mumkin emas."],
    manbalar: ["Moore va boshqalar ROMA validation studies", "Ishlatiladigan HE4 va CA-125 assay yo'riqnomasi"],
  },
  {
    slug: 'iota-simple-rules',
    nomi: 'IOTA Simple Rules',
    kategoriya: 'Onkoginekologiya',
    qisqaIzoh: "Adneksal massani beshta benign va beshta malign UTT belgisi orqali tasniflaydi.",
    batafsilIzoh: "IOTA Simple Rules standart transvaginal UTT terminologiyasidan foydalanadi. Faqat B-belgilar bo'lsa benign, faqat M-belgilar bo'lsa malign, ikkala tur yoki hech biri bo'lmasa noaniq natija beriladi.",
    maydonlar: ["Unilokulyar kista", "Eng katta solid komponent", "Akustik soya", "Silliq multilokulyar o'sma", "Qon oqimi yo'qligi", "Noto'g'ri solid o'sma", "Ascit", "Kamida 4 papillyar tuzilma", "Noto'g'ri multilokulyar-solid massa", "Juda kuchli qon oqimi"],
    hisoblash: ["Faqat B belgilar: benign.", "Faqat M belgilar: malign.", "B va M birga yoki ikkalasi ham yo'q: inconclusive."],
    natijaTalqini: ["Noaniq holat ekspert UTT, ADNEX modeli yoki onkoginekologik bahoni talab qiladi."],
    cheklovlar: ["IOTA terminlari bo'yicha o'qitilgan UTT mutaxassisi o'lchovi zarur.", "Bu gistologik tashxis emas."],
    manbalar: ["IOTA Group Simple Rules validation studies", "IOTA terminology consensus"],
  },
  {
    slug: 'iota-adnex',
    nomi: 'IOTA ADNEX modeli',
    kategoriya: 'Onkoginekologiya',
    qisqaIzoh: "Adneksal massaning benign yoki to'rtta malign guruhdan biriga mansublik xavfini hisoblaydi.",
    batafsilIzoh: "ADNEX modeli benign, borderline, I bosqich invaziv, II-IV bosqich invaziv va ikkilamchi metastatik o'sma ehtimollarini beradi. CA-125 bilan yoki usiz variant mavjud.",
    maydonlar: ["Yosh", "Onkologiya markazi yoki boshqa muassasa", "CA-125 ixtiyoriy", "Massa maksimal diametri", "Solid qism diametri", "Lokulalar soni", "Papillyar proyeksiyalar soni", "Akustik soya", "Ascit"],
    hisoblash: ["Rasmiy IOTA ADNEX modeli yoki tasdiqlangan implementatsiya ishlatiladi; koeffitsiyentlar taxminan yozilmaydi."],
    natijaTalqini: ["Har bir toifa uchun foizlar va umumiy malignlik xavfi ko'rsatiladi.", "Yo'naltirish cutoffi mahalliy protokolga bog'liq."],
    cheklovlar: ["Operatsiya rejalashtirilayotgan adneksal massa populyatsiyasida qo'llanadi.", "Skrining va gistologiya o'rnini bosmaydi.", "Rasmiy modelning foydalanish va litsenziya shartlari tekshiriladi."],
    manbalar: ["Van Calster va boshqalar BMJ 2014 ADNEX model", "IOTA Group official tools"],
  },
  {
    slug: 'cervical-cancer-risk',
    nomi: "Bachadon bo'yni CIN3 plyus xavfini ASCCP bo'yicha baholash",
    kategoriya: 'Onkoginekologiya',
    qisqaIzoh: "Joriy va oldingi HPV, sitologiya, biopsiya hamda davolash tarixiga asoslanib CIN3+ xavfini va keyingi klinik qadamni aniqlaydi.",
    batafsilIzoh: "Bu oddiy ball kalkulyatori emas. ASCCP modeli bemorning joriy natijalarini oldingi skrining va davolash tarixi bilan birlashtirib darhol va 5 yillik CIN3+ xavfini hisoblaydi.",
    maydonlar: ["Yosh", "Homiladorlik holati", "Joriy HPV natijasi va genotipi", "Joriy sitologiya", "Oldingi HPV va sitologiya", "Kolposkopiya yoki biopsiya", "Oldingi CIN2+ davolashi"],
    hisoblash: ["ASCCPning joriy rasmiy risk jadvali yoki web ilovasi ishlatiladi.", "Risk chegaralari klinik harakatga xaritalanadi."],
    natijaTalqini: ["Natija kuzatuv, 1 yoki 3 yillik qayta tekshiruv, kolposkopiya, yoki ayrim yuqori xavf holatlarda tezlashtirilgan davolash kabi harakatni ko'rsatadi."],
    cheklovlar: ["Oddiy ommaviy saraton xavfi yoki simptomli bemor diagnostikasi uchun emas.", "Qo'llanma yangilanib turadi; statik nusxa eskirishi mumkin.", "Rasmiy ASCCP modeliga havola berish xavfsizroq."],
    manbalar: ["2019 ASCCP Risk Based Management Consensus Guidelines", "ASCCP Enduring Guidelines and official web application"],
  },
  {
    slug: 'pfiq-7',
    nomi: "PFIQ 7 tos tubi buzilishining hayot sifatiga ta'siri",
    kategoriya: 'Uroginekologiya',
    qisqaIzoh: "Siydik, prolaps va kolorektal simptomlarning kundalik hayotga ta'sirini baholaydi.",
    batafsilIzoh: "PFIQ-7 uchta 7 savollik subshkaladan iborat: UIQ-7, CRAIQ-7 va POPIQ-7. Har bir faoliyat bo'yicha 0 dan 3 gacha ta'sir baholanadi.",
    maydonlar: ["Rasmiy yoki validatsiya qilingan PFIQ-7 javoblari"],
    hisoblash: ["Har subshkalaning javoblar o'rtachasi x 100 / 3.", "Uch subshkala qo'shiladi; jami 0-300."],
    natijaTalqini: ["Yuqori ball hayot sifatiga ta'sir kuchliroq ekanini bildiradi.", "Davolashdan oldin va keyin dinamikani solishtirish foydali."],
    cheklovlar: ["Universal yengil-o'rta-og'ir cutofflar yo'q.", "Savollarni platformaga joylashdan oldin mualliflik, foydalanish va o'zbekcha validatsiya masalasi hal qilinadi."],
    manbalar: ["Barber va boshqalar AJOG 2005 PFDI-20 and PFIQ-7 validation"],
  },
  {
    slug: 'pfdi-20',
    nomi: 'PFDI 20 tos tubi simptomlari so rovnomasi',
    kategoriya: 'Uroginekologiya',
    qisqaIzoh: "Prolaps, kolorektal-anal va siydik simptomlarining bezovtalik darajasini baholaydi.",
    batafsilIzoh: "PFDI-20 uch subshkaladan iborat: POPDI-6, CRADI-8 va UDI-6. Har simptom mavjudligi va qanchalik bezovta qilishi baholanadi.",
    maydonlar: ["Rasmiy yoki validatsiya qilingan 20 savolga javoblar"],
    hisoblash: ["Har subshkalada javoblar o'rtachasi x 25.", "Uch subshkala qo'shiladi; jami 0-300."],
    natijaTalqini: ["Yuqori ball simptom yukining kattaligini bildiradi.", "Dinamika davolash samaradorligini kuzatishga yordam beradi."],
    cheklovlar: ["Tashxis yoki POP-Q anatomik bosqichini almashtirmaydi.", "Rasmiy tarjima va foydalanish shartlari tekshiriladi."],
    manbalar: ["Barber va boshqalar AJOG 2005 PFDI-20 and PFIQ-7 validation"],
  },
  {
    slug: 'pop-q',
    nomi: 'POP Q klassifikatsiyasi',
    kategoriya: 'Uroginekologiya',
    qisqaIzoh: "Tos a'zolari prolapsini gimen tekisligiga nisbatan standart nuqtalar bilan bosqichlaydi.",
    batafsilIzoh: "POP-Q kalkulyatordan ko'ra standart anatomik o'lchov va klassifikatsiya vositasidir. Aa, Ba, C, D, Ap va Bp nuqtalari santimetrda, TVL, gh va pb o'lchamlari bilan qayd etiladi.",
    maydonlar: ["Aa", "Ba", "C", "D agar serviks mavjud bo'lsa", "Ap", "Bp", "TVL", "gh", "pb"],
    hisoblash: ["Eng distal prolaps nuqtasi gimen tekisligiga nisbatan aniqlanadi.", "Bosqich 0 dan 4 gacha ICS mezonlari bilan belgilanadi."],
    natijaTalqini: ["0: prolaps yo'q.", "1: distal nuqta gimen ustidan 1 sm dan yuqori.", "2: distal nuqta gimendan -1 sm dan +1 sm gacha.", "3: +1 sm dan past, ammo TVL-2 sm dan kam.", "4: deyarli to'liq eversiya."],
    cheklovlar: ["O'lchov Valsalva yoki maksimal zo'riqishda to'g'ri bajariladi.", "Anatomik bosqich simptom og'irligi bilan har doim mos kelmaydi.", "Noto'g'ri birlik va musbat-manfiy belgilarni validatsiya qilish kerak."],
    manbalar: ["ICS IUGA POP-Q standardization documents", "Bump va boshqalar AJOG 1996"],
  },
  {
    slug: 'iciq-ui-sf',
    nomi: 'ICIQ UI SF siydik tutolmaslik shkalasi',
    kategoriya: 'Uroginekologiya',
    qisqaIzoh: "Siydik tutolmaslik chastotasi, hajmi va hayot sifatiga ta'sirini baholaydi.",
    batafsilIzoh: "ICIQ-UI SF to'rtta banddan iborat. Uchta ball beriladigan band jami 0-21 ni hosil qiladi; to'rtinchi band holatlarni aniqlashga yordam beradi va jami ballga kirmaydi.",
    maydonlar: ["Chastota", "Oqib ketadigan siydik miqdori", "Kundalik hayotga ta'siri", "Qachon oqib ketishi haqidagi diagnostik band"],
    hisoblash: ["Ball beriladigan uch band qo'shiladi; jami 0-21."],
    natijaTalqini: ["1-5 yengil.", "6-12 o'rta.", "13-18 og'ir.", "19-21 juda og'ir."],
    cheklovlar: ["Sabab yoki urodinamik tashxisni aniqlamaydi.", "ICIQ modullari mualliflik huquqi bilan himoyalangan; ruxsat va validatsiya qilingan tarjima talab qilinadi."],
    manbalar: ["ICIQ official validation and translation guidance", "Avery va boshqalar Neurourology and Urodynamics 2004"],
  },
]

// Ro'yxatdagi 25 nomning beshtasi alohida aniq model tanlanmasdan xavfsiz
// implementatsiya qilinmaydi. Ular uchun quyidagi qarorlar qabul qilinishi kerak:
// 1. Preeklampsiya: ACOG xavf omillari yoki litsenziyalangan FMF modeli.
// 2. VBAC: irq koeffitsiyentisiz validatsiya qilingan NICHD/MFMU modeli.
// 3. AMH: qaysi assay va yoshga xos referens jadvali.
// 4. ROMA: qaysi HE4/CA-125 assay platformasi va uning cutofflari.
// 5. FRAX va ADNEX: rasmiy vositaga havola/API yoki foydalanish ruxsati.

