// Urologiyada ishlatiladigan tasniflar — talaba bo'limidagi ma'lumotnoma.
//
// Bu yerda faqat keng qabul qilingan, darslik darajasidagi tasniflar turadi.
// Har birida manba va nashr yili ko'rsatilgan: tasniflar vaqti-vaqti bilan
// qayta ko'rib chiqiladi, shuning uchun klinik qaror qabul qilishda amaldagi
// gaydlar bilan solishtirish kerak.
//
// Yangi tasnif qo'shish: shu faylga yozish kifoya, sahifa o'zi ko'rsatadi.

export type Tasnif = {
  slug: string
  nom: string
  toliq?: string // inglizcha to'liq nomi
  kategoriya: string
  maqsad: string // nimani tasniflaydi
  qachon: string // klinik amaliyotda qachon ishlatiladi
  manba: string
  ustunlar: string[]
  qatorlar: string[][]
  izoh?: string // ehtiyot bo'lish kerak bo'lgan nuqta
}

export const TASNIF_KATEGORIYALARI = [
  'Hammasi',
  "Buyrak va siydik yo'llari",
  "Yallig'lanish",
  'Onkourologiya',
  'Andrologiya',
  'Simptom shkalalari',
  'Jarrohlik',
] as const

export const TASNIFLAR: Tasnif[] = [
  // ─────────────────────────── Buyrak va siydik yo'llari
  {
    slug: 'bosniak',
    nom: 'Bosniak tasnifi',
    toliq: 'Bosniak classification of renal cysts',
    kategoriya: "Buyrak va siydik yo'llari",
    maqsad: "Buyrak kistalarini KT/MRT ko'rinishiga qarab xavflilik darajasiga ajratadi.",
    qachon: "Tasodifan topilgan buyrak kistasi bilan nima qilish kerakligini hal qilishda: kuzatuvmi, takroriy tekshiruvmi yoki operatsiyami.",
    manba: 'Bosniak, 1986 · 2019 yilda qayta ko\'rib chiqilgan',
    ustunlar: ['Toifa', "Ko'rinishi", 'Xavf', 'Nima qilinadi'],
    qatorlar: [
      ['I', "Oddiy kista: devori yupqa va silliq, ichida to'siq yo'q, suv zichligida", '~0%', 'Kuzatuv kerak emas'],
      ['II', "Uchtagacha yupqa to'siq, mayda kalsifikatsiya", '~0–1%', 'Kuzatuv kerak emas'],
      ['IIF', "To'siqlar ko'proq, devor biroz qalinlashgan, kontrast to'plamaydi", '~5%', 'Takroriy tasvirlash bilan kuzatuv'],
      ['III', "Qalin, notekis to'siq yoki devor — kontrast to'playdi", '~50%', 'Operatsiya yoki biopsiya'],
      ['IV', "Kontrast to'playdigan yumshoq to'qima komponenti bor", '~90%', 'Operatsiya'],
    ],
    izoh: "IIF toifasi aynan kuzatuv uchun ajratilgan — u darhol operatsiya talab qilmaydi, lekin e'tiborsiz ham qoldirilmaydi.",
  },
  {
    slug: 'sfu-gidronefroz',
    nom: 'Gidronefroz darajalari (SFU)',
    toliq: 'Society for Fetal Urology grading',
    kategoriya: "Buyrak va siydik yo'llari",
    maqsad: "Buyrak jomi va kosachalarining kengayish darajasini UTT bo'yicha baholaydi.",
    qachon: "Gidronefroz aniqlanganda og'irligini belgilash va kuzatuv davomida o'zgarishni solishtirish uchun.",
    manba: 'Society for Fetal Urology, 1993',
    ustunlar: ['Daraja', 'UTT manzarasi'],
    qatorlar: [
      ['0', "Kengayish yo'q"],
      ['1', 'Faqat buyrak jomi biroz kengaygan'],
      ['2', "Jom va ba'zi kosachalar kengaygan"],
      ['3', "Jom va barcha kosachalar kengaygan, parenxima qalinligi normal"],
      ['4', '3-darajaga qo\'shimcha: parenxima yupqalashgan'],
    ],
    izoh: "Parenxima yupqalashuvi — 3 va 4-darajani ajratuvchi asosiy belgi. Aynan u buyrak funksiyasi yo'qolayotganini ko'rsatadi.",
  },
  {
    slug: 'vur',
    nom: 'Sistoureteral reflyuks darajalari',
    toliq: 'Vesicoureteral reflux (VUR) grading',
    kategoriya: "Buyrak va siydik yo'llari",
    maqsad: "Siydikning qovuqdan siydik nayiga qaytish darajasini tasniflaydi.",
    qachon: "Mikstsion sistouretrografiya (MSUG) natijasini baholashda; davolash tanlashda (kuzatuv, antibiotik profilaktikasi yoki operatsiya).",
    manba: 'International Reflux Study Committee, 1985',
    ustunlar: ['Daraja', "Ko'rinishi"],
    qatorlar: [
      ['I', "Faqat siydik nayiga qaytadi, kengayish yo'q"],
      ['II', "Jom va kosachalargacha yetadi, lekin kengaymagan"],
      ['III', 'Yengil–o\'rta kengayish, kosacha burchaklari biroz yumshagan'],
      ['IV', "O'rtacha kengayish va egrilik, kosacha burchaklari yumaloqlashgan"],
      ['V', "Kuchli kengayish va egrilik, so'rg'ich izlari yo'qolgan"],
    ],
    izoh: "I–III darajalar ko'pincha o'z-o'zidan tuzaladi; IV–V da operativ davolash ehtimoli yuqori.",
  },
  {
    slug: 'kdigo-ckd',
    nom: 'Surunkali buyrak kasalligi (KDIGO)',
    toliq: 'KDIGO CKD classification',
    kategoriya: "Buyrak va siydik yo'llari",
    maqsad: "Buyrak funksiyasini koptokchalar filtratsiya tezligi (GFR) bo'yicha bosqichlarga ajratadi.",
    qachon: "Dori dozasini moslashda, nefrologga yo'naltirishda va operatsiya oldidan xavfni baholashda.",
    manba: 'KDIGO, 2012',
    ustunlar: ['Bosqich', 'GFR (ml/min/1.73m²)', 'Izoh'],
    qatorlar: [
      ['G1', '≥ 90', "Normal yoki yuqori — buyrak shikasti belgisi bo'lsa"],
      ['G2', '60–89', 'Yengil pasaygan'],
      ['G3a', '45–59', "Yengil–o'rta pasaygan"],
      ['G3b', '30–44', "O'rta–kuchli pasaygan"],
      ['G4', '15–29', 'Kuchli pasaygan'],
      ['G5', '< 15', "Buyrak yetishmovchiligi — o'rnini bosuvchi davolash"],
    ],
    izoh: "GFR ning o'zi yetarli emas: albuminuriya (A1–A3) bilan birga baholanadi.",
  },
  {
    slug: 'aast-buyrak',
    nom: 'Buyrak travmasi (AAST)',
    toliq: 'AAST kidney injury scale',
    kategoriya: "Buyrak va siydik yo'llari",
    maqsad: 'Buyrak shikastlanishining og\'irligini KT bo\'yicha darajalaydi.',
    qachon: "Travmada operativ aralashuv kerakmi yoki konservativ kuzatuv yetarlimi — shuni hal qilishda.",
    manba: 'AAST, 1989 · 2018 da qayta ko\'rib chiqilgan',
    ustunlar: ['Daraja', 'Shikastlanish'],
    qatorlar: [
      ['I', "Kontuziya yoki kapsula ostidagi gematoma, yorilish yo'q"],
      ['II', "Buyrak atrofidagi cheklangan gematoma; yorilish 1 sm dan kam"],
      ['III', '1 sm dan chuqur yorilish, chiqaruv tizimi shikastlanmagan'],
      ['IV', "Yorilish chiqaruv tizimiga yetgan (siydik chiqishi) yoki segmentar tomir shikasti"],
      ['V', "Buyrak parchalangan yoki asosiy tomir uzilgan"],
    ],
    izoh: "Ko'pchilik I–III darajalar konservativ davolanadi. 2018 tahririda tomir shikastlari darajalarga aniqroq taqsimlangan.",
  },

  // ─────────────────────────── Yallig'lanish
  {
    slug: 'nih-prostatit',
    nom: 'Prostatit tasnifi (NIH)',
    toliq: 'NIH classification of prostatitis',
    kategoriya: "Yallig'lanish",
    maqsad: "Prostatit sindromlarini sabab va yallig'lanish belgilariga qarab to'rt toifaga ajratadi (III toifa ikkiga bo'linadi).",
    qachon: "Prostatit shikoyati bilan kelgan bemorda davolash yo'nalishini tanlashda — antibiotikmi yoki simptomatik davolashmi.",
    manba: 'National Institutes of Health, 1995',
    ustunlar: ['Toifa', 'Nomi', 'Asosiy belgisi'],
    qatorlar: [
      ['I', "O'tkir bakterial prostatit", "O'tkir boshlanish, isitma, og'ir holat"],
      ['II', 'Surunkali bakterial prostatit', "Takrorlanuvchi infeksiya, bir xil qo'zg'atuvchi"],
      ['IIIA', "Yallig'lanishli CPPS", "Sekretda leykotsit bor, ekma manfiy"],
      ['IIIB', "Yallig'lanishsiz CPPS", "Leykotsit ham, ekma ham manfiy"],
      ['IV', "Asemptomatik yallig'lanishli prostatit", "Shikoyat yo'q, tasodifan topiladi"],
    ],
    izoh: "III toifa (CPPS) eng ko'p uchraydi va antibiotikka javob bermaydi — bu talabalar ko'p yanglishadigan nuqta.",
  },
  {
    slug: 'qsofa',
    nom: 'qSOFA — sepsis xavfi',
    toliq: 'quick Sequential Organ Failure Assessment',
    kategoriya: "Yallig'lanish",
    maqsad: 'Infeksiyasi bor bemorda hayot uchun xavfli kechishni tezda aniqlaydi.',
    qachon: "Urosepsis shubhasida — laboratoriya natijasini kutmasdan, karavot yonida.",
    manba: 'Sepsis-3, 2016',
    ustunlar: ['Belgi', 'Chegara'],
    qatorlar: [
      ['Nafas olish tezligi', '≥ 22 marta/daqiqa'],
      ['Ong holati', "O'zgargan (GCS < 15)"],
      ['Sistolik bosim', '≤ 100 mm Hg'],
    ],
    izoh: "Uchtadan ikkitasi bo'lsa — yuqori xavf, zudlik bilan chora ko'riladi. qSOFA tashxis emas, saralash vositasi.",
  },

  // ─────────────────────────── Onkourologiya
  {
    slug: 'isup-gleason',
    nom: 'ISUP daraja guruhlari (Gleason)',
    toliq: 'ISUP Grade Groups / Gleason score',
    kategoriya: 'Onkourologiya',
    maqsad: 'Prostata saratonining gistologik agressivligini baholaydi.',
    qachon: "Biopsiya natijasini talqin qilishda va davolash tanlashda (kuzatuvmi yoki radikal davolashmi).",
    manba: 'ISUP, 2014 · WHO 2016 dan rasmiy',
    ustunlar: ['Guruh', 'Gleason ball', 'Ma\'nosi'],
    qatorlar: [
      ['1', '≤ 6 (3+3)', 'Past xavf — faol kuzatuv mumkin'],
      ['2', '7 (3+4)', "Oraliq, qulay"],
      ['3', '7 (4+3)', 'Oraliq, noqulay'],
      ['4', '8', 'Yuqori xavf'],
      ['5', '9–10', 'Juda yuqori xavf'],
    ],
    izoh: "3+4 va 4+3 — ikkalasi ham 7 ball, lekin prognozi boshqacha. Shuning uchun daraja guruhlari kiritilgan.",
  },
  {
    slug: 'tnm-prostata',
    nom: 'Prostata saratoni — T bosqichi',
    toliq: 'TNM staging, prostate (T category)',
    kategoriya: 'Onkourologiya',
    maqsad: "O'smaning prostata ichida va tashqarisida tarqalishini belgilaydi.",
    qachon: "Davolash rejasini tuzishda: lokalizatsiyalangan, mahalliy tarqalgan yoki metastatik kasallikni ajratishda.",
    manba: 'AJCC/UICC TNM, 8-nashr',
    ustunlar: ['Bosqich', "Ta'rifi"],
    qatorlar: [
      ['T1', "Paypaslanmaydi va tasvirlashda ko'rinmaydi (tasodifan yoki biopsiyada topiladi)"],
      ['T2', 'Prostata ichida cheklangan'],
      ['T3a', 'Kapsuladan tashqariga chiqqan'],
      ['T3b', "Urug' pufakchasiga tarqalgan"],
      ['T4', "Qo'shni a'zolarga o'sgan (qovuq bo'yni, to'g'ri ichak, chanoq devori)"],
    ],
    izoh: "T bosqichi yolg'iz ishlatilmaydi — PSA va ISUP guruhi bilan birga xavf guruhini beradi.",
  },
  {
    slug: 'nmibc-xavf',
    nom: 'Qovuq o\'smasi — mushakka o\'tmagan shakl',
    toliq: 'Non-muscle-invasive bladder cancer (NMIBC) risk groups',
    kategoriya: 'Onkourologiya',
    maqsad: "TURBT dan keyin qaytalanish va progressiya xavfini guruhlarga ajratadi.",
    qachon: "Operatsiyadan keyin qo'shimcha davolash (BCG yoki kimyoterapiya) kerakmi — shuni hal qilishda.",
    manba: 'EAU gaydlari asosida',
    ustunlar: ['Guruh', 'Odatda nimani anglatadi'],
    qatorlar: [
      ['Past xavf', "Yolg'iz, birinchi marta, kichik, past darajali Ta o'sma"],
      ["O'rta xavf", 'Past va yuqori guruhga tushmaydigan holatlar'],
      ['Yuqori xavf', "Yuqori darajali, T1, CIS, yoki ko'p sonli va tez qaytalanuvchi"],
    ],
    izoh: "Aniq mezonlar gaydning tahririga qarab o'zgaradi — davolash tanlashda amaldagi EAU jadvalidan foydalaning.",
  },

  // ─────────────────────────── Andrologiya
  {
    slug: 'dubin-amelar',
    nom: 'Varikotsele darajalari',
    toliq: 'Dubin–Amelar grading',
    kategoriya: 'Andrologiya',
    maqsad: 'Varikotselening klinik og\'irligini ko\'rish va paypaslash orqali belgilaydi.',
    qachon: "Operatsiyaga ko'rsatma berishda va davolashdan keyingi natijani solishtirishda.",
    manba: 'Dubin & Amelar, 1970',
    ustunlar: ['Daraja', 'Aniqlanishi'],
    qatorlar: [
      ['I', 'Faqat Valsalva sinamasi paytida paypaslanadi'],
      ['II', "Tinch holatda ham paypaslanadi, lekin ko'rinmaydi"],
      ['III', "Yorg'oq terisi ostidan ko'z bilan ko'rinadi"],
    ],
    izoh: "Subklinik varikotsele bu shkalaga kirmaydi — u faqat UTT/dopplerda aniqlanadi va odatda davolanmaydi.",
  },
  {
    slug: 'who-spermogramma',
    nom: 'Spermogramma me\'zonlari',
    toliq: 'WHO laboratory manual, 6th edition',
    kategoriya: 'Andrologiya',
    maqsad: "Sperma ko'rsatkichlarining quyi chegara qiymatlarini belgilaydi.",
    qachon: "Erkaklar bepushtligini tekshirishda spermogramma natijasini talqin qilishda.",
    manba: 'WHO, 2021 (6-nashr)',
    ustunlar: ["Ko'rsatkich", 'Quyi chegara'],
    qatorlar: [
      ['Hajm', '≥ 1.4 ml'],
      ['Konsentratsiya', '≥ 16 mln/ml'],
      ['Umumiy son', '≥ 39 mln'],
      ['Umumiy harakatchanlik', '≥ 42%'],
      ['Progressiv harakatchanlik', '≥ 30%'],
      ['Normal morfologiya', '≥ 4%'],
      ['Tiriklik', '≥ 54%'],
    ],
    izoh: "Bu chegaralar «norma» emas — fertil erkaklarning quyi 5% i. Bitta tahlil yetarli emas, 2–3 marta takrorlanadi.",
  },
  {
    slug: 'ehs',
    nom: 'Ereksiya qattiqligi shkalasi',
    toliq: 'Erection Hardness Score (EHS)',
    kategoriya: 'Andrologiya',
    maqsad: 'Ereksiya sifatini to\'rt bosqichda tez baholaydi.',
    qachon: "Anketa to'ldirishga vaqt bo'lmaganda; davolash samarasini kuzatishda.",
    manba: 'EAU tomonidan tavsiya etilgan',
    ustunlar: ['Ball', 'Holat'],
    qatorlar: [
      ['1', "Kattalashadi, lekin qattiq emas"],
      ['2', "Qattiq, lekin jinsiy aloqa uchun yetarli emas"],
      ['3', "Aloqa uchun yetarli, lekin to'liq qattiq emas"],
      ['4', "To'liq qattiq va mustahkam"],
    ],
  },
  {
    slug: 'iief5',
    nom: 'IIEF-5 og\'irlik darajalari',
    toliq: 'International Index of Erectile Function, 5-item',
    kategoriya: 'Andrologiya',
    maqsad: 'Erektil disfunksiya og\'irligini anketa balli bo\'yicha belgilaydi.',
    qachon: "Tashxisni rasmiylashtirish va davolashdan oldin/keyin solishtirish uchun.",
    manba: 'Rosen va boshq., 1999',
    ustunlar: ['Ball', 'Daraja'],
    qatorlar: [
      ['22–25', "Buzilish yo'q"],
      ['17–21', 'Yengil'],
      ['12–16', "Yengil–o'rta"],
      ['8–11', "O'rta"],
      ['5–7', "Og'ir"],
    ],
  },

  // ─────────────────────────── Simptom shkalalari
  {
    slug: 'ipss',
    nom: 'IPSS — simptom og\'irligi',
    toliq: 'International Prostate Symptom Score',
    kategoriya: 'Simptom shkalalari',
    maqsad: "Pastki siydik yo'llari simptomlarining og'irligini 7 savol orqali o'lchaydi.",
    qachon: "BPH da davolashni boshlashda va samarasini kuzatishda.",
    manba: 'AUA / WHO, 1992',
    ustunlar: ['Ball', 'Daraja', 'Odatda nima qilinadi'],
    qatorlar: [
      ['0–7', 'Yengil', "Kuzatuv va turmush tarzini o'zgartirish"],
      ['8–19', "O'rta", 'Dori davolashni boshlash uchun asos'],
      ['20–35', "Og'ir", "Dori davolash, samarasiz bo'lsa operatsiya"],
    ],
    izoh: "8 ball — davolash boshlash uchun amaliy chegara. Alohida hayot sifati savoli (0–6) ham hisobga olinadi.",
  },
  {
    slug: 'oab-v8',
    nom: 'OAB-V8 — giperaktiv qovuq',
    toliq: 'Overactive Bladder Awareness Tool',
    kategoriya: 'Simptom shkalalari',
    maqsad: 'Giperaktiv qovuq simptomlarini skrining qiladi.',
    qachon: "Tez-tez va shoshilinch siyish shikoyatlarida keyingi tekshiruvga asos berishda.",
    manba: 'Coyne va boshq., 2005',
    ustunlar: ['Ball', "Ma'nosi"],
    qatorlar: [
      ['< 8', 'Giperaktiv qovuq ehtimoli past'],
      ['≥ 8', 'Ehtimol bor — batafsil tekshiruv kerak'],
    ],
  },
  {
    slug: 'uroflow',
    nom: 'Uroflowmetriya me\'zonlari',
    toliq: 'Uroflowmetry interpretation',
    kategoriya: 'Simptom shkalalari',
    maqsad: "Siydik oqimining eng yuqori tezligini (Qmax) baholaydi.",
    qachon: "Siyish qiyinlashuvida obstruksiya bor-yo'qligini dastlabki baholashda.",
    manba: 'Klinik amaliyotda qabul qilingan me\'zonlar',
    ustunlar: ['Qmax', "Ma'nosi"],
    qatorlar: [
      ['> 15 ml/s', 'Odatda normal'],
      ['10–15 ml/s', 'Chegaraviy — talqin ehtiyot bilan'],
      ['< 10 ml/s', 'Obstruksiya ehtimoli yuqori'],
    ],
    izoh: "Siyilgan hajm 150 ml dan kam bo'lsa natija ishonchsiz — tekshiruv takrorlanadi.",
  },

  // ─────────────────────────── Jarrohlik
  {
    slug: 'clavien-dindo',
    nom: 'Clavien–Dindo tasnifi',
    toliq: 'Clavien–Dindo classification of surgical complications',
    kategoriya: 'Jarrohlik',
    maqsad: "Operatsiyadan keyingi asoratlarni ular talab qilgan davolash bo'yicha darajalaydi.",
    qachon: "Asoratlarni qayd qilishda va turli markazlar natijalarini solishtirishda.",
    manba: 'Dindo, Demartines & Clavien, 2004',
    ustunlar: ['Daraja', "Ta'rifi"],
    qatorlar: [
      ['I', "Odatdagi kechishdan chetlanish; dori (og'riq qoldiruvchi, isitma tushiruvchi kabi) va aralashuv talab qilmaydi"],
      ['II', "I darajadan tashqari dori davolash, qon quyish yoki parenteral ovqatlantirish"],
      ['IIIa', "Aralashuv kerak, umumiy narkozsiz"],
      ['IIIb', 'Aralashuv kerak, umumiy narkoz ostida'],
      ['IVa', "Hayot uchun xavfli — bitta a'zo yetishmovchiligi, reanimatsiya"],
      ['IVb', "Ko'p a'zo yetishmovchiligi"],
      ['V', "Bemorning o'limi"],
    ],
    izoh: "Daraja asoratning o'zi bilan emas, uni bartaraf etish uchun nima qilinganiga qarab beriladi.",
  },
  {
    slug: 'asa',
    nom: 'ASA — anesteziologik xavf',
    toliq: 'ASA Physical Status Classification',
    kategoriya: 'Jarrohlik',
    maqsad: "Bemorning operatsiya oldidagi umumiy holatini baholaydi.",
    qachon: "Operatsiya oldidan xavfni baholashda va anesteziya rejasini tuzishda.",
    manba: 'American Society of Anesthesiologists',
    ustunlar: ['Sinf', 'Holat'],
    qatorlar: [
      ['I', "Sog'lom bemor"],
      ['II', 'Yengil tizimli kasallik'],
      ['III', "Og'ir tizimli kasallik, faoliyatni cheklaydi"],
      ['IV', 'Hayot uchun doimiy xavf soluvchi kasallik'],
      ['V', "O'lim arafasida, operatsiyasiz yashashi kutilmaydi"],
      ['VI', "Miya o'limi — a'zo donori"],
    ],
  },
  {
    slug: 'charlson',
    nom: 'Charlson indeksi',
    toliq: 'Charlson Comorbidity Index',
    kategoriya: 'Jarrohlik',
    maqsad: "Yondosh kasalliklar yig'indisini ball bilan o'lchab, uzoq muddatli yashash ehtimolini bashorat qiladi.",
    qachon: "Agressiv davolash foyda keltiradimi yoki bemorga zarar bo'ladimi — shuni tortishda.",
    manba: 'Charlson va boshq., 1987',
    ustunlar: ['Ball', "Ma'nosi"],
    qatorlar: [
      ['0', 'Yondosh kasallik yo\'q'],
      ['1–2', "Yengil yuk"],
      ['3–4', "O'rta yuk"],
      ['≥ 5', "Og'ir yuk — prognoz sezilarli yomonlashadi"],
    ],
    izoh: "Onkologik bemorda muhim: o'sma emas, yondosh kasallik hayot davomiyligini belgilab qo'yishi mumkin.",
  },
  {
    slug: 'renal-nefrometriya',
    nom: 'R.E.N.A.L. nefrometriya',
    toliq: 'R.E.N.A.L. nephrometry score',
    kategoriya: 'Jarrohlik',
    maqsad: "Buyrak o'smasining anatomik murakkabligini beshta belgi bo'yicha ball bilan o'lchaydi.",
    qachon: "Qisman nefrektomiya texnik jihatdan mumkinmi yoki radikal olib tashlash kerakmi — shuni rejalashtirishda.",
    manba: 'Kutikov & Uzzo, 2009',
    ustunlar: ['Harf', 'Nimani baholaydi'],
    qatorlar: [
      ['R', "O'sma o'lchami (Radius)"],
      ['E', "Ekzofit yoki endofit joylashuvi"],
      ['N', "Chiqaruv tizimiga yaqinligi (Nearness)"],
      ['A', "Old yoki orqa yuzada (Anterior/Posterior)"],
      ['L', "Qutblarga nisbatan joylashuvi (Location)"],
    ],
    izoh: "Umumiy ball qancha yuqori bo'lsa, a'zo saqlovchi operatsiya shuncha murakkab.",
  },
]
