BEGIN;

ALTER TABLE public.telegram_posts
  ADD COLUMN IF NOT EXISTS telegram_message_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS sent_to_destination_id uuid REFERENCES public.telegram_destinations(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_error text;

ALTER TABLE public.telegram_posts
  DROP CONSTRAINT IF EXISTS telegram_posts_message_ids_array,
  ADD CONSTRAINT telegram_posts_message_ids_array CHECK (jsonb_typeof(telegram_message_ids) = 'array');

CREATE TABLE IF NOT EXISTS public.telegram_post_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id uuid NOT NULL REFERENCES public.telegram_posts(id) ON DELETE CASCADE,
  revision integer NOT NULL CHECK (revision > 0),
  snapshot jsonb NOT NULL CHECK (jsonb_typeof(snapshot) = 'object'),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (post_id, revision)
);

ALTER TABLE public.telegram_post_revisions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.telegram_post_revisions FROM anon, authenticated;
GRANT SELECT, INSERT ON public.telegram_post_revisions TO authenticated;
GRANT ALL ON public.telegram_post_revisions TO service_role;
CREATE POLICY admin_read_post_revisions ON public.telegram_post_revisions
  FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY admin_insert_post_revisions ON public.telegram_post_revisions
  FOR INSERT TO authenticated WITH CHECK (public.is_admin());

CREATE INDEX IF NOT EXISTS telegram_post_revisions_post ON public.telegram_post_revisions(post_id, revision DESC);

COMMIT;
