-- Kunlik tibbiy yangiliklar: manbalar, moderatsiya va cron auditi.

CREATE TABLE IF NOT EXISTS public.yangilik_manbalari (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  feed_url text NOT NULL UNIQUE,
  source_url text NOT NULL,
  category text NOT NULL CHECK (category IN ('urologiya', 'andrologiya', 'ginekologiya')),
  enabled boolean NOT NULL DEFAULT true,
  priority integer NOT NULL DEFAULT 100,
  may_reuse_official_images boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.yangiliklar (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  source_name text NOT NULL,
  source_url text NOT NULL UNIQUE,
  source_date timestamptz,
  original_title text NOT NULL,
  title_uz text,
  summary_uz text,
  content_uz text,
  category text NOT NULL CHECK (category IN ('urologiya', 'andrologiya', 'ginekologiya')),
  importance text NOT NULL DEFAULT 'normal' CHECK (importance IN ('normal', 'high', 'critical')),
  student_importance text,
  doctor_importance text,
  patient_importance text,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'published', 'rejected', 'failed')),
  dedup_hash text NOT NULL UNIQUE,
  image_url text,
  image_source_url text,
  image_credit text,
  telegram_message_id text,
  telegram_status text NOT NULL DEFAULT 'pending' CHECK (telegram_status IN ('pending', 'sent', 'failed', 'skipped')),
  telegram_error text,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.yangilik_ishlari (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_at timestamptz NOT NULL DEFAULT now(),
  -- Production cron sana yozadi; admin testlari NULL bo'lib, cron kalitini band qilmaydi.
  run_key date UNIQUE,
  status text NOT NULL CHECK (status IN ('running', 'completed', 'failed', 'skipped')),
  candidates_found integer NOT NULL DEFAULT 0,
  published_count integer NOT NULL DEFAULT 0,
  error_message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.yangilik_xato_loglari (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id uuid REFERENCES public.yangilik_ishlari(id) ON DELETE CASCADE,
  source_id uuid REFERENCES public.yangilik_manbalari(id) ON DELETE SET NULL,
  news_id uuid REFERENCES public.yangiliklar(id) ON DELETE SET NULL,
  stage text NOT NULL,
  error_message text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS yangiliklar_status_idx ON public.yangiliklar(status, created_at DESC);
CREATE INDEX IF NOT EXISTS yangiliklar_category_idx ON public.yangiliklar(category, source_date DESC);
CREATE INDEX IF NOT EXISTS yangiliklar_published_idx ON public.yangiliklar(published_at DESC) WHERE status = 'published';
CREATE INDEX IF NOT EXISTS yangilik_manbalari_enabled_idx ON public.yangilik_manbalari(enabled, priority);
CREATE INDEX IF NOT EXISTS yangilik_ishlari_run_idx ON public.yangilik_ishlari(run_at DESC);
CREATE INDEX IF NOT EXISTS yangilik_xato_loglari_run_idx ON public.yangilik_xato_loglari(run_id, created_at DESC);

-- Ishonchli boshlang'ich feed. Keng NIH oqimidan mavzuga oid yozuvlargina kodda
-- urologiya/andrologiya/ginekologiya kalit so'zlari bilan saralanadi.
INSERT INTO public.yangilik_manbalari (name, feed_url, source_url, category, priority, may_reuse_official_images)
VALUES (
  'NIH News Releases',
  'https://www.nih.gov/news-events/news-releases/rss.xml',
  'https://www.nih.gov/news-events/news-releases',
  'urologiya', 10, false
)
ON CONFLICT (feed_url) DO UPDATE SET
  name = EXCLUDED.name, source_url = EXCLUDED.source_url, enabled = true,
  priority = EXCLUDED.priority, may_reuse_official_images = EXCLUDED.may_reuse_official_images;

ALTER TABLE public.yangiliklar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.yangilik_manbalari ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.yangilik_ishlari ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.yangilik_xato_loglari ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "published_yangiliklarni_oqish" ON public.yangiliklar;
CREATE POLICY "published_yangiliklarni_oqish" ON public.yangiliklar
  FOR SELECT USING (
    status = 'published'
    OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "admin_yangiliklarni_boshqaradi" ON public.yangiliklar;
CREATE POLICY "admin_yangiliklarni_boshqaradi" ON public.yangiliklar
  FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "admin_yangilik_manbalari" ON public.yangilik_manbalari;
CREATE POLICY "admin_yangilik_manbalari" ON public.yangilik_manbalari
  FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "admin_yangilik_ishlari" ON public.yangilik_ishlari;
CREATE POLICY "admin_yangilik_ishlari" ON public.yangilik_ishlari
  FOR SELECT USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "admin_yangilik_xato_loglari" ON public.yangilik_xato_loglari;
CREATE POLICY "admin_yangilik_xato_loglari" ON public.yangilik_xato_loglari
  FOR SELECT USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- Banner qaysi yangilikdan yaratilganini bilish va qayta cronlarda takrorlamaslik uchun.
ALTER TABLE public.bannerlar ADD COLUMN IF NOT EXISTS yangilik_id uuid REFERENCES public.yangiliklar(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS bannerlar_yangilik_role_unique
  ON public.bannerlar(yangilik_id, target_role);

-- Rol ajratilishi faqat UI filtriga bog'liq qolmaydi.
DROP POLICY IF EXISTS "Faol bannerlarni hamma ko'ra oladi" ON public.bannerlar;
DROP POLICY IF EXISTS "bannerlar_select" ON public.bannerlar;
DROP POLICY IF EXISTS "rolga_mos_faol_bannerlar" ON public.bannerlar;
CREATE POLICY "rolga_mos_faol_bannerlar" ON public.bannerlar
  FOR SELECT USING (
    faol = true AND arxiv = false
    AND (boshlanish IS NULL OR boshlanish <= now())
    AND (tugash IS NULL OR tugash >= now())
    AND (
      target_role IS NULL OR target_role = 'hamma'
      OR (auth.uid() IS NULL AND target_role = 'landing')
      OR target_role = (SELECT role FROM public.profiles WHERE id = auth.uid())
    )
  );
